### ISSUE TITLE
Composable file idea

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1038]
We are collecting thoughts on this idea. Let us know what you think :)

## Problem
It's difficult to reason about top level organizational concepts (datasets, tasks, etc.) when there are multiple files that are related to each other directly.

For example
1) Multiple views that are related to each other (different camera angles for example)
2) Multiple pages of a document

People end up having to twist their heads thinking about, create many things etc.
Besides not being a great product experience it puts unexpected strain on random parts of the system, eg. things that normal should be fine listing 10 or 100 objects suddenly need to scale to smoothly load 10k etc. 

## Solution

The idea is you could define your "one thing" as these a collection of media files.
Then you can treat it like a normal file in Diffgram.

So instead of having say 20 images, and then grouping it into a task, then having a burdensome volume of datasets/task templates etc, you create 1 Composable file that has 20 children image files,
and the can use the rest of the Organizational objects as normal.

Example super rough:
![image](https://user-images.githubusercontent.com/18080164/187762123-07c88224-0652-4051-ab9c-46e994d70880.png)

May use the current file browser card to show hidden files. 
e.g. user closes a file it goes there
or not open files can be added to main screen from there

The min/restore/close buttons are oversized on diagram vs expected real size / visibility 
diagram shows many files at once, can start with just two, etc.

## Further Context
The context is seeing a lot of people run into concerns trying to setup organizational schemes, when many would be quite easy if they could just define what "one" thing was for their context. 

The main point is that you define what "one thing" means.
This way it removes a lot of the stress around having so many jobs, datasets etc.

Please note this is closely related to but different implementation wise from sensor fusion, video, generally having it in a set etc. It's more about creating a first class citizen for a training data specific organizational problem.

DB relations and other docs see internal

## Considerations

Example considerations
* Creating tasks for each child file automatically, or config for what "done" is considered
* Config on reporting
In general this would assume it will default that completing a Composable file means one task.

Naming ideas
* Composable
* Compound
* Multi

**Comment by PJEstrada** [comment]
# SDK Side
We'll need an API to be able to build and ingest these composable files.
Initial ideas:

```
from diffgram.file.composable import ComposabelFile

comp_file = ComposableFile()
img1 = File.new_from_url(url='some_url')
img2 = File.new_from_url(url='some_url2')
# Add files to composed file
comp_file.add(img1, ordering = 1, tags= ['file1'])
comp_file.add(img2, ordering = 2, tags= ['file1'])

# upload
com_file.upload()
```

**Comment by anthony-sarkis** [comment]
V1 of this was completed so archiving this as Complete and closing.
