### ISSUE TITLE
docker-compose: ERROR: unknown blob

### ISSUE THREAD

**Issue by ainnotate** [diffgram/diffgram#1058]
Hi, I'm trying to setup diffgram on Ubuntu 20.04, using instructions given [here](https://diffgram.readme.io/docs/install).

I've setup AWS S3 as my storage and everything goes fine. At last, the docker-compose up -d command fails with the below error. To me this looks like some issue related to the docker images. Am I missing something? Could someone throw some light?

`
Pulling db_migration (gcr.io/diffgram-open-core/default:1.8.4)...
1.8.4: Pulling from diffgram-open-core/default
27833a3ba0a5: Downloading
ad5023f26108: Downloading
35cace2fde21: Downloading
89a6b3b8082f: Downloading
88e577cb069e: Downloading
981bf79bcca8: Download complete
0c4498431a76: Download complete
b3285ba6b47f: Download complete
cb4e98242471: Download complete
6db16584372c: Download complete
c7e38fc310a9: Download complete
7b60437c8fe8: Download complete
f144ae085a4e: Download complete
a3c37019c14a: Download complete
b225d187ee51: Download complete
ERROR: unknown blob
` 

Thank you.

**Comment by vitalii-bulyzhyn** [comment]
Hey @ainnotate !

I've just tried to install the latest version of Diffgram and everything seems to work fine, can you give more details on your setup?

**Comment by ainnotate** [comment]
Hi @vitalii-bulyzhyn,() 

OS: Ubuntu 20.04
Docker version 20.10.18, build b40c2f6
diffgram version: latest (1.8.4) 

Note: the git repo is on the HEAD of master branch, which is 1.8.4

We also tried on a Windows machine and we found the same problem.

Is there any dependency with the docker version?

**Comment by vitalii-bulyzhyn** [comment]
It should not be dependent dependent on version of docker

I'll forward this issue to @PJEstrada, and he will take a look on the issue early next week

**Comment by ainnotate** [comment]
The issue seems to be with the walrus service. I'm able to successfully build other services individually. 

`docker compose up --no-deps --build walrus`

**Comment by PJEstrada** [comment]
Hi @ainnotate 

Thanks for sharing the issue. It was a problem with our container registry. It should be fixed now.

Try re running the docker compose command now. I'll close the issue but please re open if you still have issues
