### ISSUE TITLE
New Dataset - access_type: Missing access_type

### ISSUE THREAD

**Issue by ainnotate** [diffgram/diffgram#1061]
Hi,

Diffgram version: 1.8.6

I've setup diffgram on my localhost.

I'm trying to create a new dataset and I get this error.  I've gone through the documentation [here](https://diffgram.readme.io/docs/viewing-files-file-management) and couldn't find any setting or other information related to this error. Could someone help, please?

![image](https://user-images.githubusercontent.com/89445176/191451743-6a22ff39-fd00-4cf8-a450-88f49e11c79d.png)

**Comment by vitalii-bulyzhyn** [comment]
Hey @ainnotate, thanks for reporting that
