### ISSUE TITLE
upload EntityTooSmall

### ISSUE THREAD

**Issue by lackray** [diffgram/diffgram#1075]
After #1070,now i can upload.During uploading,comes another exception.
**this is my console error:**
![image](https://user-images.githubusercontent.com/19989329/192928061-09051543-ccf8-4cb5-a266-38068fd84858.png)
**so,i go to check the docker-walrus,it gives me this:**
![image](https://user-images.githubusercontent.com/19989329/192928346-db1af355-8027-4557-8b25-644195f594da.png)

There is no minimum limitation of multipart upload on S3 API of minio server. 
![image](https://user-images.githubusercontent.com/19989329/192930779-2e5c7b1b-9c32-40ff-95e3-c27f3e7cc4f9.png)

How can i change the code inside `shared/data_tools_core_s3.py` line 153? @PJEstrada 

Here is my temporary solution,i comment out the `MultipartUpload` inside `shared/data_tools_core_s3.py` line 148-154 related.
When i start to run the upload script,minio server connection error occurs.This is werid,i dont know why.Is this about message queue jam issue?Sometimes when i start upload script,the message queue dont handle it.MQ always do the heartbeat check,just miss the real job!
![image](https://user-images.githubusercontent.com/19989329/192987176-aacf6236-3e3e-4d76-a052-fe3058db8a75.png)

After several tries,finally i get upload worked.I dont do anything except restarting all diffgram docker services.
![image](https://user-images.githubusercontent.com/19989329/192988377-15be162e-3977-4ec6-bd93-c5fbdd44f0e7.png)

Saddly there is always a but,here comes an error.
![image](https://user-images.githubusercontent.com/19989329/192989043-dda1c1bf-a1a7-43dd-8fc1-b85a0751f2fd.png)
docker hosted diffgram view:
![image](https://user-images.githubusercontent.com/19989329/192989244-598399ac-d6a2-4a8c-8297-f3bbdc520a25.png)
I go to check the minio buckets page,there is no uploaded file.
![image](https://user-images.githubusercontent.com/19989329/192989956-5d8cb17d-5f1f-4357-800b-ad3ec547125f.png)

Does it mean my file uploading fail?I dont know how to edit code inside `shared/data_tools_core_s3.py`,it seems that my temporary solution will lead to unexpected errors.

**Comment by PJEstrada** [comment]
Hey @lackray thanks a lot for the thorough description.

I think the solution might be easier than we think. We have an env variable that control the chunk size for large uploads on the UI:

https://github.com/diffgram/diffgram/blob/93e1b4b4a1deae926461f0ec28c480d868162bcb/shared/settings/settings.py#L179

You can set this env variable to a larger size and hopefully this error should be gone.

**Comment by lackray** [comment]
> Hey @lackray thanks a lot for the thorough description.
> 
> I think the solution might be easier than we think. We have an env variable that control the chunk size for large uploads on the UI:
> 
> https://github.com/diffgram/diffgram/blob/93e1b4b4a1deae926461f0ec28c480d868162bcb/shared/settings/settings.py#L179
> 
> You can set this env variable to a larger size and hopefully this error should be gone.

It didnt work.I add 'LARGE_API_CHUNK_SIZE=15' inside `.env`,same error EntityTooSmall.Do we have to use `complete_multipart_upload`  with `MultipartUpload `?I think if file is less than 5GiB,we should upload directly without MultipartUpload .And I am not sure aboutLARGE_API_CHUNK_SIZE=5 means 5*1000*1000 or 5*1024*1024.

**Comment by PJEstrada** [comment]
One more question are you using the UI or the Python SDK for upload? If its the SDK can you share the code snippet? I'll be taking a look and get back to you with a solution.

**Comment by lackray** [comment]
> One more question are you using the UI or the Python SDK for upload? If its the SDK can you share the code snippet? I'll be taking a look and get back to you with a solution.

Im using the Python SDK for uploading point cloud file,which is the only way to upload now .Code snippet is same as https://diffgram.readme.io/docs/3d-lidar-annotation-guide(upload_3d_file_to_diffgram). Im using the sample file.My python console just returns 'internal error' for such error,so i have to check with docker-walrus console output,which i mentioned above.

**Comment by PJEstrada** [comment]
Thanks for the info!

I think the problem might be with the SDK. Previous version had a chunk size of 5mb for the 3D uploads by default. 

I have fixed this and added a `chunk_size` param to the `upload()` function on version `0.9.5` of the SDK (default also is now 6MB). 

Can you try doing:

`pip install diffgram==0.9.5`

And trying the upload again by re running the script?

**Comment by lackray** [comment]
> Thanks for the info!
> 
> I think the problem might be with the SDK. Previous version had a chunk size of 5mb for the 3D uploads by default.
> 
> I have fixed this and added a `chunk_size` param to the `upload()` function on version `0.9.5` of the SDK (default also is now 6MB).
> 
> Can you try doing:
> 
> `pip install diffgram==0.9.5`
> 
> And trying the upload again by re running the script?

Not working.Sample code runs fine,but i use my ply file larger than 94MB,it gives me this:
![image](https://user-images.githubusercontent.com/19989329/193598311-2aa140d2-ae14-4c0c-b095-16376ff64aa9.png)

![image](https://user-images.githubusercontent.com/19989329/193599192-d56273d7-75a7-46ab-a585-f796103ff566.png)

my read function:
**def read_ply_o3d(file_name):
    ply = o3d.io.read_triangle_mesh(file_name)
    out_arr = np.array(ply.vertices)
    return out_arr**
other code is same as sapmle.Dont know why,i looks like the SDK dont expect json format content.

**Comment by PJEstrada** [comment]
Can you share your full script please? That way we can fully replicate the error

**Comment by lackray** [comment]
here is my code:
from diffgram.file.file_3d import File3D
from diffgram.core.core import Project

from diffgram import *
import open3d as o3d
import numpy as np


def read_pcd_o3d(file_name):
    pcd = o3d.io.read_point_cloud(file_name)
    out_arr = np.asarray(pcd.points)
    return out_arr


def read_ply_o3d(file_name):
    ply = o3d.io.read_triangle_mesh(file_name)
    out_arr = np.array(ply.vertices)
    return out_arr


project = Project(
    # host="http://192.168.124.20:8085",
    host="http://192.168.31.174:8085",
    project_string_id="papercrane",
    client_id="LIVE__8v3cfiwr9rapp4ryxchl",
    client_secret="mhzy6aay4jn03awrx9zad15e3y5b4xqz5e54rr72qksn17a137pv6nfni0no"
)
# project = Project(
#     host="http://13.251.106.16:18088",
#     project_string_id="weedbell",
#     client_id="LIVE__180hlfk2k3p3yp0s1m68",
#     client_secret="60977ffnb7ku6jf97wwksaqqb3vig1t2djcun137wm0c7owjo2azjzki9ijf"
# )
#cloud
# project = Project(
# project_string_id = "wheatfox",
# client_id = "LIVE__ugwy8150elwphoelhza6",
# client_secret = "01o9e32yha7ia5vy1ufegt5k6fq3ciy2byd7xox3g9ao9wcalq8k2q5eru5g"
# )

# filename = 'Zaghetto.pcd'
filename = 'scan_0016.ply'

# points_arr = read_pcd_o3d(filename)
points_arr = read_ply_o3d(filename)

diffgram_3d_file = File3D(client=project, name=filename)

for i in range(0, len(points_arr)):
    point = points_arr[i]
    diffgram_3d_file.add_point(
        x=point[0],
        y=point[1],
        z=point[2],
    )
print('read point done')
diffgram_3d_file.upload()

**Comment by PJEstrada** [comment]
> here is my code:
> 
> ```
> from diffgram.file.file_3d import File3D
> from diffgram.core.core import Project
> 
> from diffgram import *
> import open3d as o3d
> import numpy as np
> 
> 
> def read_pcd_o3d(file_name):
>     pcd = o3d.io.read_point_cloud(file_name)
>     out_arr = np.asarray(pcd.points)
>     return out_arr
> 
> 
> def read_ply_o3d(file_name):
>     ply = o3d.io.read_triangle_mesh(file_name)
>     out_arr = np.array(ply.vertices)
>     return out_arr
> 
> 
> project = Project(
>     # host="http://192.168.124.20:8085",
>     host="http://192.168.31.174:8085",
>     project_string_id="papercrane",
>     client_id="LIVE__8v3cfiwr9rapp4ryxchl",
>     client_secret="mhzy6aay4jn03awrx9zad15e3y5b4xqz5e54rr72qksn17a137pv6nfni0no"
> )
> # project = Project(
> #     host="http://13.251.106.16:18088",
> #     project_string_id="weedbell",
> #     client_id="LIVE__180hlfk2k3p3yp0s1m68",
> #     client_secret="60977ffnb7ku6jf97wwksaqqb3vig1t2djcun137wm0c7owjo2azjzki9ijf"
> # )
> 
> 
> # filename = 'Zaghetto.pcd'
> filename = 'scan_0016.ply'
> 
> # points_arr = read_pcd_o3d(filename)
> points_arr = read_ply_o3d(filename)
> 
> diffgram_3d_file = File3D(client=project, name=filename)
> 
> for i in range(0, len(points_arr)):
>     point = points_arr[i]
>     diffgram_3d_file.add_point(
>         x=point[0],
>         y=point[1],
>         z=point[2],
>     )
> print('read point done')
> diffgram_3d_file.upload()
> ```

Hey @lackray,

Thanks for all the details on this. I've identify a bug on the chunking process for MinIO specifically. So I deployed v `1.8.22` please try upgrading by changing the tags, the issue should be fixed with the new version.
