### ISSUE TITLE
Unable to upload uppercase JPG from GCS

### ISSUE THREAD

**Issue by OterLabb** [diffgram/diffgram#1105]
Diffgram wont accept uppercase jpg when importing from google cloud storage, this is the error message from docker:

`walrus_1         | WARNING:root:File: DJI_202208251528_002/DJI_20220825153302_0004.JPG must type of: ['.jpg', '.jpeg', '.png'] ['.mp4', '.mov', '.avi', '.m4v', '.quicktime']`

However when uploading the same file from local computer it works.

**Comment by PJEstrada** [comment]
Thanks for reporting this, this will get fixed on release `1.9.3`
