### ISSUE TITLE
Pre-load data in task context

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1145]
Main idea is to preload some or all of the data needed so that switching tasks has user perception of feeling faster.

Analogy is like app loading on early iphones where it appeared to load like magic (and it was just a screenshot).

In theory it would take the user's perception of something that's 2-3 seconds down to <100 ms or whatever time it takes to swap items in memory and re-render.

Before we resisted this becuase usually it was more of a "micro" optimization but a few things have changed:

1. larger Schema's, meaning a different Schema by itself may take some loading time
2. more annotations, instances, attributes etc.
3. more config choices, like the custom url signer etc.

Could start with just images UI. (But concepts would carry over)
Naively one implementation could be something like

1. After load, start pre-loader:
2. Auto fetch next task, as if user clicked next
3. Store in a new cache. fetching the image data itself may require making a separate request.
4. When clicking next, check cache
5. If user exits and cache exists, try to un-assign maybe?
6. other risks /edge cases

There's some concerns here around reserving the next task, and then if the user doesn't complete it un-assigning it or something like that.

Feels like some edge cases but maybe for now the benefits to user perception maybe worth it.

Other ideas from call
* Like video frame buffer, getting previous 3, storing them next 3 etc. 
e.g. then can cycle forward or backwards
* Trigger to auto fetch would be moving forward like video buffer
* Better use property of assign/or not
e.g. API /next-task auto assigns users
e.g. query param assign_user : bool, 
so in prefetch context set to false, if user clicks button set true to the one task
Reuse assign call

* assignment ways multiple ways, maybe end user config
e.g. assigning and asking if user wants to do more
or the admin wants to control it

* main thing with assignment is blocking to prevent two people working on the same file

* seperate assignment from sent by pre-fetch?

Simple
1) V1 Fetch n number of tasks and assign them
V1 Avoid back word fetching for now since assignment problem
V2 which is if it is already assigned it can still fetch it, but don't assign it
Configurable number of pre-fetch

2) As needed we add features for detection of dead tasks 
Could be part of workflow
Example actions could be alert on performance, unassign tasks,
Example when backend fetches next task,
it could check if any tasks are no updated, and not completed, and then un-assigns user,
like walrus

**Comment by PJEstrada** [comment]
We can implement it something like this:

```

class Task {
  id: number
  file: File
  etc...
}
class TaskPrefetcher {
  cached_tasks: Task[]
  
  prefetch_next_task(current_task: Task){
    
  }

  prefetch_prev_task(current_task: Task){

  }
  
  get_next_task(current_task: Task){
    
  }
  
  get_prev_task(current_task: Task){
    
  }
  
}
```
