### ISSUE TITLE
some question about user manager

### ISSUE THREAD

**Issue by feifeizuo** [diffgram/diffgram#1146]
Hi,
        I install diffgram use docker on my server. And I set a domain name (example: diffgram.ai.com )to localhost:8085.
This domain name can be access on internet, it's means anyone can create user and create project.

Question 1: Can I forbid create user function, user only access it by invite ?
Question 2: Where can I see all the registered users and manager them( delete or something else) ?
Question 3: On project A, I invite a user Jams. On project B, it's seems I can't add Jams to project B. I must invite Jams repeat. Is this normal ?

Thanks

**Comment by anthony-sarkis** [comment]
> Question 1: Can I forbid create user function, user only access it by invite ?

Setting `DISABLE_SELF_REGISTRATION` env var to False should work
https://github.com/diffgram/diffgram/blob/master/shared/settings/settings.py#L211

> Question 2: Where can I see all the registered users and manager them( delete or something else) ?

https://diffgram.readme.io/docs/user-permissions

> Question 3: On project A, I invite a user Jams. On project B, it's seems I can't add Jams to project B. I must invite Jams repeat. Is this normal ?

Each project is it's own permission structure
See https://diffgram.readme.io/docs/concepts-101#projects
https://diffgram.readme.io/docs/tasks-and-projects

A project can have many task sets, so no need to repeat unless desired.
Check out other advanced options on the docs like custom roles and OIDC for more complex configs

**Comment by feifeizuo** [comment]
Thanks very much.
