### ISSUE TITLE
Error during labelbox migration: TypeError: get_connector() got an unexpected keyword argument 'connector_id'

### ISSUE THREAD

**Issue by AndreasVaage** [diffgram/diffgram#1156]
Small error during Labelbox migration.

![error_labelbox_migration](https://user-images.githubusercontent.com/21969695/200142786-2455799b-05ed-42d6-ad30-d9c6ed02915f.png)

As I understand it the keyword argument should be 'connection_id' instead.

**Comment by anthony-sarkis** [comment]
Thank you we will review

**Comment by PJEstrada** [comment]
Thanks for sharing @AndreasVaage.

This was already fixed on above PR and will be published on next release.

**Comment by anthony-sarkis** [comment]
Thanks Pablo!!
