### ISSUE TITLE
Change E2E Test Github Action to Use MinIO Instead of Azure Containers

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#1177]
Since all of our tests are stateless. Sometimes e2e tests become flaky do to issues with blob paths being persisted on azure storage. We can now use minio locally on the server runner to mitigate this and also to save some cloud storage costs.

**Comment by anthony-sarkis** [comment]
Amazing!!! Good going Pablo!

**Comment by PJEstrada** [comment]
Added as part of https://github.com/diffgram/diffgram/pull/1210
