### ISSUE TITLE
Offline installation tries to connect to diffgram.com

### ISSUE THREAD

**Issue by M6stafa** [diffgram/diffgram#1179]
Hi,

I installed the diffgram locally on a computer without internet. I want to use it on an interanet and don't need any internet access.
After i create a task, it keeps loading in task list. I checked the docker logs and see this error:
```
diffgram-walrus-1         | [2022-11-21 05:58:37,949] INFO event.py Line 326: Created event 2490:task_created
diffgram-walrus-1         | [2022-11-21 05:58:41,160] ERROR event.py Line 356: Exception sending HTTPSConnectionPool(host='diffgram.com', port=443): Read timed out. (read timeout=3) to Diffgram Eventhub: 
```

What should i do?

**Comment by PJEstrada** [comment]
Hi @M6stafa 

On a related note please check the values for `WALRUS_SERVICE_URL_BASE` env variable to see if it is pointing the your offline service

**Comment by anthony-sarkis** [comment]
@M6stafa Please update if still having this issue
