### ISSUE TITLE
Bug: Text search prompt linked to file search

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1191]
May be related to https://github.com/diffgram/diffgram/issues/1190

Note "ss" in search box as well as top box

![image](https://user-images.githubusercontent.com/18080164/203181080-045e8255-1699-408f-9e4d-cb5ef3728da0.png)

**Comment by vitalii-bulyzhyn** [comment]
This one is related to #1190, to replicate the bug:

- do a text selection (that fast labeling menu is open)
- print something on the input of the file manager
- after this #1190 and #1191 will appear
