### ISSUE TITLE
Bug: Add Multi-Schema to Text

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1192]
Switching between a different schema in the Studio does not refresh text.

To reproduce create two schemas and switch between them
Schema does not reload

** note the Global attributes already load, so the Schema itself is changing, just not on the text UI / prompt

![image](https://user-images.githubusercontent.com/18080164/203181438-97531071-6b87-466e-9cd8-4a6312b6716d.png)

**Comment by vitalii-bulyzhyn** [comment]
Small note: it does not refresh labels only if menu is open, if it's close and open again - labels refreshed
