### ISSUE TITLE
Project Thumnbails not displaying correctly

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#120]
For some reason thumbnails don't display correctly on all projects:

![image](https://user-images.githubusercontent.com/6606958/123323787-3f5af880-d4f3-11eb-8c61-f0be2f793b0b.png)

**Comment by anthony-sarkis** [comment]
I believe this uses the caching system. May be something off with how project thumbnail gets generated or how it's cached in the project db row
