### ISSUE TITLE
Report / approval_reject_ratio / text: 500 error:  "list index out of range"

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1202]
Not sure if it's specific to text or not

Response:
`error
: 
"list index out of range"`

![image](https://user-images.githubusercontent.com/18080164/203189129-03c2faa3-735e-4e48-a998-e73d693a7a66.png)

**Comment by PJEstrada** [comment]
Hey Anthony! I can't replicate this one on local env. Can you share any other details on the context of how this happened?
![image](https://user-images.githubusercontent.com/6606958/204057754-716ae2dd-4baa-4531-b82f-ae024584a213.png)

**Comment by anthony-sarkis** [comment]
I will message on slack :)
