### ISSUE TITLE
how to export global attributes ?

### ISSUE THREAD

**Issue by feifeizuo** [diffgram/diffgram#1221]
Hi,
     I upload some image to Dataset1, and create schemas which only container attribute(per file, just for image cls) and no labels. Then I create task and labeled all image done. 
<img width="402" alt="image" src="https://user-images.githubusercontent.com/6001243/204181429-a3c0e844-aa52-402a-8445-f5edd1c17e0c.png">

Now ,  I want export labels,
<img width="1828" alt="image" src="https://user-images.githubusercontent.com/6001243/204181577-abda121b-ab05-41b9-85e2-673c32003189.png">

as the image show, this is not file.
Have I done wrong somewhere?

Thanks vecy much.

**Comment by PJEstrada** [comment]
Hello! Can you share the error when you click on the red icon? Also what versión of diffgram do you have?

**Comment by feifeizuo** [comment]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/6001243/204454153-c17183fa-694b-4c21-8832-c6d6488007bf.png">
I have export attributes by python SDK.
And I try export in UI with small dataset(only 4 image complete), It works fine.

**Comment by PJEstrada** [comment]
Can you please check if the dataset name is not duplicated or if you have any files on that dataset?

**Comment by feifeizuo** [comment]
I will use it continue in other task, if it's going not work, I will try recurrence more details.

**Comment by anthony-sarkis** [comment]
@feifeizuo you can also export from the Task as a source. that removes any ambiguity on dataset too
Please close this if you are unable to reproduce or provide more details thank you

**Comment by feifeizuo** [comment]
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/6001243/204993707-c1f9589c-3aba-4978-80bd-5900d03ac60f.png">
After a day, it seems all export work well. Maybe take long time,.
