### ISSUE TITLE
how to replace locahost to real size in invite link?

### ISSUE THREAD

**Issue by feifeizuo** [diffgram/diffgram#1226]
Hi,
    I create project, and invite someone by them email, but the  link them receive is (http://localhost:8085/user/new?code=...), 
Can I replace localhost:8085 with my websize url(example: diffgram.mycompany.com) ?

Thanks .

**Comment by PJEstrada** [comment]
You need to change 

`URL_BASE`
Located here for reference: URL_BASE = os.getenv('URL_BASE', "http://localhost:8085/")

and if you want interservice requests to the walrus service to also go through your domain name also change: 

`WALRUS_SERVICE_URL_BASE`

Located here for reference:  https://github.com/diffgram/diffgram/blob/5b0c902f122b615c1b5980cfcc0ac28ae7d01b10/shared/settings/settings.py#L105


You can read more about configs here:  https://diffgram.readme.io/docs/settings-environment-variables-and-secrets

**Comment by feifeizuo** [comment]
thanks
