### ISSUE TITLE
Not able to draw anything after Polygon is finished

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [diffgram/diffgram#1244]
Way to replicate:
1. Open video for annotating
2. Select Polygon type
3. Draw Polygon
4. Error will be on the console and you won't be able to draw anything else

<img width="405" alt="Screenshot 2022-12-08 at 10 49 07" src="https://user-images.githubusercontent.com/46309116/206415116-57376910-aeaf-4305-b9f4-f9a7869d1f74.png">

**Comment by anthony-sarkis** [comment]
https://github.com/diffgram/diffgram/commit/fe9f6c11bf2ed201a1c1becbac6aef023d759fb8
