### ISSUE TITLE
Invalid COG GEO files created and show unexpected state in Annotation UI

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1250]
It throws expected error on input, but still creates the file, which is unexpected.

The file then throws `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'url_signed')` 
and shows a white screen in annotation UI. Example file attached as zip below

![image](https://user-images.githubusercontent.com/18080164/208204731-fffbd53c-c80d-430a-a06e-0f6c84c8a870.png)

[o41078a7.zip](https://github.com/diffgram/diffgram/files/10249977/o41078a7.zip)

**Comment by vitalii-bulyzhyn** [comment]
Can be replicated with this file:

https://ieee-dataport.org/open-access/sierra-nevada-snow-2001-2019-validation-spires

**Comment by vitalii-bulyzhyn** [comment]
Here is the solution: https://www.cogeo.org/developers-guide.html
