### ISSUE TITLE
COG surface open layer errors to user

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1251]
processes as valid file but then throws
`4.ec26184d747b1bab8b6b.js:1 AssertionError: Assertion failed. See https://openlayers.org/en/v6.14.1/doc/errors/#17 for details.`

Similar to how we handle showing the end user UI message for broken signed URLs
let's do something similar here
e.g. to surface that assertion to the end user
otherwise right now they just see checkmark on upload and then white screen

from https://corteva.github.io/rioxarray/stable/examples/COG.html
and attached

[5d7dad0becaf880008a9bc89.zip](https://github.com/diffgram/diffgram/files/10250019/5d7dad0becaf880008a9bc89.zip)

![image](https://user-images.githubusercontent.com/18080164/208208459-74074fd6-09f0-4589-9cb8-7ffc40a75bda.png)

**Comment by vitalii-bulyzhyn** [comment]
Seems to be related to [this](https://github.com/geotiffjs/geotiff.js/issues/281) and [this](https://github.com/openlayers/openlayers/issues/13349) issues

From what I understand, that it's still valid COG but that's something related to hot GeoTiff.js handles it
