### ISSUE TITLE
Geo, dark overlay appears unexpectedly

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1253]
Video on slack

**Comment by vitalii-bulyzhyn** [comment]
From what I saw on the video, I only can make an assumption that file that was uploaded was just black layer and since we are setting opacity for GeoTiff layer as 0.5, that's where you got that "mask" from. If you can share that file - I will confirm if that's true

**Comment by anthony-sarkis** [comment]
File https://drive.google.com/file/d/1L2q_xtlZkRByjZ0KOjpqQ6bXc9lebUby/view?usp=share_link

That makes sense Vitalii thank you for explaining. Closing since nothing to fix
