### ISSUE TITLE
Geo, unexpectedly zooms out 

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1254]
Video and example file on slack

**Comment by vitalii-bulyzhyn** [comment]
Wasn't able to replicate this one, maybe you can give me a bit more details how to replicate it?

**Comment by anthony-sarkis** [comment]
file link https://drive.google.com/file/d/1puqRNS8HlgPSiNl3nn9UcZNRhKlHKsyq/view?usp=share_link

**Comment by anthony-sarkis** [comment]
Setting low priority unless comes up with other peoples files. 

I only observed it with that file. 
To reproduce as shown on video mainly just annotating and randomly zooming in and out before hand. then every 3rd or so annotation it seemed to happen.

**Comment by anthony-sarkis** [comment]
This appears to have been from the bounds issue so I believe it was fixed
