### ISSUE TITLE
Text Relations in Json File

### ISSUE THREAD

**Issue by opallch** [diffgram/diffgram#1292]
Hi, I have annotated the text with two labels ("Aspect" with label id 2502672 and "Opinion" with label id 2502673) and also the relation as follow:

![grafik](https://user-images.githubusercontent.com/76699397/214056344-fde0170d-7d24-45cf-94b0-054394f09c3b.png)

All the instances, including the annotated token(s) and the annotated relation are supposedly stored under `<FILE_ID>` > `instance_list`but I could find anything related to the relation. This is what I get in the `instance_list`:
```
type:text_token
label_file_id:2502672
frame_number:None
global_frame_number:None
number:None
x_min:0
y_min:0
x_max:0
y_max:0
lonlat:None
coords:None
radius:None
bounds:None
bounds_lonlat:None
p1:None
p2:None
cp:None
angle:0.0
attribute_groups:None
interpolated:False
start_char:None
end_char:None
start_token:1
end_token:1
start_sentence:None
end_sentence:None
sentence:None
====================================
type:text_token
label_file_id:2502673
frame_number:None
global_frame_number:None
number:None
x_min:0
y_min:0
x_max:0
y_max:0
lonlat:None
coords:None
radius:None
bounds:None
bounds_lonlat:None
p1:None
p2:None
cp:None
angle:0.0
attribute_groups:None
interpolated:False
start_char:None
end_char:None
start_token:0
end_token:0
start_sentence:None
end_sentence:None
sentence:None
====================================
type:global
label_file_id:None
frame_number:None
global_frame_number:None
number:None
x_min:None
y_min:None
x_max:None
y_max:None
lonlat:None
coords:None
radius:None
bounds:None
bounds_lonlat:None
p1:None
p2:None
cp:None
angle:0.0
attribute_groups:None
interpolated:False
====================================
```

My questions are:
1. Where is the information about the annotated relations stored?
2. What does global type mean i.e. what is actually the last instance in my output?

Thx in advance!

**Comment by vitalii-bulyzhyn** [comment]
Hey @opallch !

Thanks for pointing that out, indeed we did not include relations to the export. We will send a fix for that within a few hours

About the global, we use that instance to apply attributes to the entire file, you can read more here: https://diffgram.readme.io/docs/global-attributes

**Comment by opallch** [comment]
hello @vitalii-bulyzhyn,

I have now generated the export file again, but I still could not find any relation annotation in the json file. I am using diffgram,com instead of the docker installation. Is there anything I have missed? Thanks!

**Comment by anthony-sarkis** [comment]
Hello @opallch 
deployed that tag here https://github.com/diffgram/diffgram/actions/runs/4000075970
so should now work on diffgram.com playground

**Comment by vitalii-bulyzhyn** [comment]
@opallch just tested on the diffgram.com, please let us know if there are still problems on your end

**Comment by opallch** [comment]
@anthony-sarkis @vitalii-bulyzhyn  Now it works! Thank you for the quick fix!
