### ISSUE TITLE
[Text Annotation] Multiple labels for the same Token 

### ISSUE THREAD

**Issue by opallch** [diffgram/diffgram#1298]
Hi!
Currently I haven't found any solution to assign more than one labels to one single token or the same token span. It would be nice to have this feature, or is there already any trick to this that I have missed? Thanks a lot!

**Comment by vitalii-bulyzhyn** [comment]
Hey @opallch !

Right, there should be a possibility to that, and we will try to get back to fix that as soon as possible. But for now you can use attributes as workaround to this problem

Also, we are always welcome external contributions

**Comment by opallch** [comment]
@vitalii-bulyzhyn Thank you for the quick response and quick fix! I would also like to contribute but unfortunately I know nothing about it... But again, thank you so much for your contribution, I do really appretiate it!
