### ISSUE TITLE
Compound file preview

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1300]
Already have `compound_file_preview.vue` working
but missing some prop when passing to task list

![image](https://user-images.githubusercontent.com/18080164/214920469-33b620e1-fcbb-4e40-9df8-260167fa31c7.png)

**Comment by PJEstrada** [comment]
Added here: https://github.com/diffgram/diffgram/pull/1234/commits/3e35a7cde4ac526b1084560ceace517e98fd9f77

**Comment by anthony-sarkis** [comment]
Awesome!
