### ISSUE TITLE
[Text Annotation] Free Text Attributes cannot be saved

### ISSUE THREAD

**Issue by opallch** [diffgram/diffgram#1305]
Hi there again! There are two things I would like to point out:

1) I have tried out the free text attributes and they could not be saved properly (neither in the UI or in the json file). 
2) It would be nice to have an attribute type which combines the radio button (or select) and the free text, that means if all of the options given are not suitable, the annotator can create a label by typing in some free text. But this is really a nice-to-have. 

Thank you in advance!

**Comment by vitalii-bulyzhyn** [comment]
Hey @opallch !

Thanks for pointing out text attribute, that should we fixed today. 

About number 2, I see your point, but that one is not on our pipeline for now

**Comment by anthony-sarkis** [comment]
You can have multiple attributes. So you can use the radio and the free
text. That should achieve a fairly similar effect.

**Comment by opallch** [comment]
Thank you for the fix! The text can now be found in the json file, but in the UI if I click on the instance again, the free text that I have typed in is not shown (the name of the attribute group is shown instead).

**Comment by vitalii-bulyzhyn** [comment]
@opallch maybe you can make a short video? I've tested and didn't notice bug you are mentioning
