### ISSUE TITLE
Support plain-text data upload

### ISSUE THREAD

**Issue by feynmanliang** [diffgram/diffgram#1327]
As a diffgram system integrator, in order to import conversation messages in real-time with minimal latency I should be able to submit a HTTP request with a string body to the diffgram platform.

* The solution should not require a disk IO, so that requests can be submitted from a browser

**Comment by anthony-sarkis** [comment]
Added!

SDK
`project.file.from_text_data(file_name=file_name, text_data=text_data)`
Full example
https://diffgram.readme.io/docs/ingesting-instances-from-mongodb-tutorial
