### ISSUE TITLE
Support for webp image format

### ISSUE THREAD

**Issue by MathijsNL** [diffgram/diffgram#1330]
Hi there, it has been a while!

It seems that there is no support for webp image format. Since it seems to be gaining traction it might be a good idea to support it.

Do we want support for webp in diffgram? If so, what are the requirements for the original media and the facing media?

**Comment by anthony-sarkis** [comment]
Great to hear from you @MathijsNL 

webp sounds great.

FYI the team is super engaged on existing pipeline so may be a little while before we can add this one

**Comment by MathijsNL** [comment]
Will try to add it over the weekend. My preliminary research suggests that webp behaves different to png files.

Issue #596 shows the effect of compression level on file size. Having compression 0 makes it basically a bmp file.

I made a similar table for webp:

compress quality | Time | Filesize | Percentage
-- | -- | -- | --
0 | 0.88 | 1392288 | 79.86
10 | 0.67 | 1392288 | 79.86
20 | 0.66 | 1392288 | 79.86
30 | 0.99 | 1226932 | 82.25
40 | 1.01 | 1226932 | 82.25
50 | 1.05 | 1227176 | 82.25
60 | 1.18 | 1227176 | 82.25
70 | 1.27 | 1227176 | 82.25
80 | 1.41 | 1227176 | 82.25
90 | 1.88 | 1222032 | 82.32
100 | 3.16 | 1218826 | 82.37

I used PIL with the following save command:
```
img_lossy = img.save(output_file, "WEBP", lossless=True, quality=compress_level)
```

**Comment by PJEstrada** [comment]
Nice to see you overe here @MathijsNL :) 

I did a quick test with a webp url on our frontend UI editor for images and the image seems to be rendering correctly with webp signed urls. So probably we can use it without further pre processing.

**Comment by MathijsNL** [comment]
@PJEstrada I just finished the research about compression, and it is not needed to do anything about that either. I will add the code soon and create a PR for it.

**Comment by anthony-sarkis** [comment]
Awesome!
