### ISSUE TITLE
Hotkeys not working properly

### ISSUE THREAD

**Issue by straussa97** [diffgram/diffgram#1338]
Hi, 
I am testing diffgram and it looks really cool but I figured out some problems.
I really like to label data by using shortcuts. But if I am pressing the suggested buttons they are not always working.
The biggest problem is to set the label for a  tag of an image. 
Is this normal or am I doing something wrong?

**Comment by PJEstrada** [comment]
Hello! Can you share with us what are the specific hotkeys that are not working? We can take a look. Can you determine the moment when they work vs when the dont work?

**Comment by straussa97** [comment]
Hi,
So my task is to classify images with multi labels.
Therefore I can use tags. For tagging an image I have to press "T" . That
is working but tagging with an special labels from the beginning on is not
possible.
Nevertheless it is possible go choose the label afterwards.Therefore also
hotkeys are available, but these are not working.
For going to the next image and saving the task there also exists a hotkey
and I figures out that this is working sometimes and sometimes not.

Is this a problem on my site or from the tool?

Best,
Sabrina

Am Do., 16. März 2023 um 14:00 Uhr schrieb PJEstrada <
***@***.***>:

**Comment by anthony-sarkis** [comment]
@straussa97  I'm going to close this issue as stale, please feel free to re-open if fresh information.
A screen share video showing the problem would be great too, thank you
