### ISSUE TITLE
Docker/Minio / Blank images in tasks

### ISSUE THREAD

**Issue by mruiu** [diffgram/diffgram#1371]
Hello, we installed the dev stack using the docker compose. We choose minio and the default local database.

Unfortunately many times we are getting blank thumbnails and blank images in tasks. From minio console the images are downloadable and look good.

this is a screenshot

![immagine](https://user-images.githubusercontent.com/132594393/236663381-f4edec31-bcf1-4eba-87c9-95863d1a837b.png)

can you help to address this ?

![immagine](https://user-images.githubusercontent.com/132594393/236663412-f4836ca3-dbb4-488a-9bd4-193f8161948b.png)

**Comment by mruiu** [comment]
if we access the ui from the same machine, sometimes works and sometimes not.

If we access from remote (from a brower on another workstation) all images are always blank.

**Comment by PJEstrada** [comment]
Hi @mruiu thanks for sharing. Can you please share with us what version of Difffram you are using?

Also is this something that happens always or do you experience it intermittently? Can you give us a bit more information on how you upload the images to get to this state and in what cases its working as expected.

Thanks again!

**Comment by PJEstrada** [comment]
> if we access the ui from the same machine, sometimes works and sometimes not.
> 
> If we access from remote (from a brower on another workstation) all images are always blank.

Reading this comment, the problem is that MinIO is hosted locally on the machine and it is not exposed to the network. You might need to change the MinIO URL to reflect the IP of the machine instead of localhost to get it to work on a local network

**Comment by mruiu** [comment]
Hi,

the version tag is 1.18.9
we use the install procedure and minio has been created automatically.

we uploadaed the images using diffgram ui, the images have been stored to minio correctly but in the tasks they appear blank.

**Comment by mruiu** [comment]
Hi, I have just re-installed everything using the install.py script tp download the latest 1.20.0 release.

Same result

minio is good

![immagine](https://user-images.githubusercontent.com/132594393/236669057-d3dc4a5c-200f-4085-befb-d7166075fe0f.png)

tasks are blank

![immagine](https://user-images.githubusercontent.com/132594393/236669077-ba731b81-b466-478e-9d87-796fe42035b7.png)

always urls with localhost in f12 debug console

**Comment by anthony-sarkis** [comment]
@mruiu Is this the preview image only or the actual task when you annotate? 
 What is the console error in the network tab? (not JS but network)
