### ISSUE TITLE
Labels appear not loading (both regular view and explorer) 

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#143]
Context: New View Only for Public Projects 

For this new view
https://diffgram.com/studio/annotate/coco-dataset

While testing from incognito,

The labels don't appear to load 
![image](https://user-images.githubusercontent.com/18080164/125355329-bd076c80-e319-11eb-917d-ce0a5720f42d.png)

I'm not sure if this is related, but the auto suggest then is getting 500 and not showing the labels
![image](https://user-images.githubusercontent.com/18080164/125355389-d4465a00-e319-11eb-8e8b-580e9e374b43.png)

Interestingly refreshing the page causes labels to load:
![image](https://user-images.githubusercontent.com/18080164/125355446-eaecb100-e319-11eb-8543-2f40dafdaf23.png)

But the explorer continues to throw 500. this is traceback
```
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/shared/permissions/project_permissions.py", line 64, in inner
    return func(*args, **kwds)
  File "/app/methods/query_engine/query_suggest.py", line 40, in query_suggest_web
    client_id = request.authorization.get('username', None)
AttributeError: 'NoneType' object has no attribute 'get'
```
Maybe some assumptions about availability of this in new "allow if public" context?

**Comment by anthony-sarkis** [comment]
Context of testing this new thing again now that prior 403 was fixed

**Comment by anthony-sarkis** [comment]
This is blocking promotion of this new feature but otherwise is not customer impacting

**Comment by PJEstrada** [comment]
Hey Anthony thanks for the info on this one: I've fixed it here: https://github.com/diffgram/diffgram/pull/144

**Comment by anthony-sarkis** [comment]
Thanks Pablo!!
