### ISSUE TITLE
Option to create labels automatically at magic import stage

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#153]
Context that a user may desire to have all the new labels created automatically.

This an option becuase the validation at this step is still valuable.

For example, maybe it could say
"We Discovered x new labels (show list of them)"
Would you like to automatically create them? (yes/no)

**Comment by PJEstrada** [comment]
This is currently supported in versions  >= 0.7.5:

![image](https://user-images.githubusercontent.com/6606958/126347952-03a31777-98c7-473e-ba02-07fa578b7111.png)


Will close for now and if there are any improvements to existing feature we can reopen or create a new one :)
