### ISSUE TITLE
DataToolsGCP AttributeError, object has no attribute \'bucket\'

### ISSUE THREAD

**Issue by MathijsNL** [diffgram/diffgram#1598]
After upgrading Diffgram from an older version to latest release (1.25.0) everything seems to be working fine. There are a few datasets where the browser gives en error on some datasets and I can't really seem to debug the cause of this:

```
{'error': {'default_url_regenerate': 'Traceback (most recent call last):\n File "/app/shared/url_generation.py", line 54, in default_url_regenerate\n blob_object.url_signed = data_tools.build_secure_url(blob_object.url_signed_blob_path, new_offset_in_seconds)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/app/shared/data_tools_core_gcp.py", line 248, in build_secure_url\n blob = self.bucket.blob(blob_name)\n ^^^^^^^^^^^\nAttributeError: \'DataToolsGCP\' object has no attribute \'bucket\'\n'}, 'info': {}, 'success': False}

```

Images still seem to load fine as well as the annotations. Hope you have any ideas about this!

**Comment by MathijsNL** [comment]
Apparently I misconfigured something in the docker compose which caused some of the services to not start op properly. Closing the issue.

**Comment by oss-maintainer-12** [comment]
@MathijsNL  Glad it was resolved! :)
