### ISSUE TITLE
Long term sync from Dataset to task not working

### ISSUE THREAD

**Issue by cvm-int** [diffgram/diffgram#173]
A Task was created related to a Dataset but when more files were imported to the Dataset, the number of files in task did not increased. 

Task was created with long term sync (see screenshot attached). Dataset currently has 17, 919 but task has 17, 617.
I will appreciate your kind support on this issue.

![image](https://user-images.githubusercontent.com/73854485/126921665-2b2b8f8b-c984-439d-a8b6-eda2e353799d.png)
![image](https://user-images.githubusercontent.com/73854485/126921882-f9a40660-2427-4542-b5de-e59c4623dfc4.png)
![image](https://user-images.githubusercontent.com/73854485/126921766-fa5c788d-1004-4b38-a55a-433440084ef1.png)

**Comment by PJEstrada** [comment]
Hi @cvm-int !
Thanks for sharing this issue with us. In order to get to the root cause of this I wanted to ask for a bit more information,

1, Can you go to the "Stream Events" section in the project menu and check if there are any pending/failed stream events?
2. Did you notice any error on the logs during the uploads of the files?
3. Did you turned off the docker containers anytime during the upload?

As a workaround, we'll work on a force resync on missing files buttton so you can re sync the tasks of the dataset.

**Comment by cvm-int** [comment]
Hi, thanks for replying. 
There are no 'failed' stream events and during the upload there was an error on the import UI  saying that it 'surpassed the limit per directory'. In my case, all files were downloaded on 'Default' folder so I had to transfer files to a diferent folder in order to reload the 'failed' imports. After that, there were no more error related to that. Pd: What is the limit of files per directory?

During the upload I had to stop docker containers because we had an issue with [max connection pool](https://github.com/diffgram/diffgram/issues/171)

**Comment by PJEstrada** [comment]
Hey @cvm-int ,

Thanks for the information. I see, so what I'm suspecting is that if you moved the files to the folder binded with the sync engine only by using a postgres query, the sync engine would not get triggered. In this case, for future references, I would suggest just to move them using the Diffgram UI or SDK so that we can generate all the events to update the tasks on the sync engine.

For the file transfer limit we currently have a hard limit of 90,000. May I know how much file you are planning to add so we can increase that limit on a future release?

**Comment by cvm-int** [comment]
So I moved the files from 'Default' to 'Batch1' using the API (See below script). Sending files via the API will not update sync between Dataset and Task? What are my options?

My total dataset is around  360,000 images but I separated into 20 batches.

```
def move_file_between_datasets (file_id, source_directory_id, destination_directory_id):
    url = "{}/api/v1/project/{}/file/transfer".format(diffgram_ip, project_string_id)
    headers = {"content-type": "application/json", "Accept": "application/json", "Authorization": authorization_code}
    payload = {
        'mode': 'TRANSFER',
        'file_list': [
            {
                'id': file_id
            }
        ],
        'source_directory_id' : source_directory_id,
        'select_from_meta_data': False,
        'transfer_action': 'move',
        'copy_instances': True,
        'destination_directory_id': destination_directory_id,
        'metadata_proposed': {}
    }
    response = requests.post(url, json=payload, headers=headers)
    print('\tstatus_code', response.status_code)
    return response.status_code, response.text
```

**Comment by PJEstrada** [comment]
Hey @cvm-int,

I just tried your code snippet on my env and trying to move the files using your snippet does work and should trigger the SyncEngine. Please try it with a single file and let me know if the task appears. We'll let you know when we have the resync button so you can sync the rest of the other files.

For the 360,000 files as long as each dataset is less than 90,000 you should be good. But we'll increase this number on the next release so you don't have problems with this.

**Comment by cvm-int** [comment]
Now that I have files to transfer, I run the script and this is the screenshot on 'Sync Events'.
![image](https://user-images.githubusercontent.com/73854485/127095732-e447b11e-10f6-4b3b-b268-46ea07a76fa0.png)

I will be kindly waiting for the 'resync button' because I still have the issue that the task is not showing updated dataset. 

Thank you very much.

**Comment by PJEstrada** [comment]
Hi @cvm-int,

We've implemented the resync button on the newest release 0.7.11: https://github.com/diffgram/diffgram/releases/tag/0.7.11

You can read how to update the system here: 
https://diffgram.readme.io/docs/open-core-docker-install-cheatsheet
Please give it a try and if you have any other issue feel free to open a new issue or discussion.

**Comment by cvm-int** [comment]
Thanks a lot, that was pretty fast.
I clicked on the button but I don't see any sync event on the 'Sync Events' page related to the task I am trying to update .
Is there any log from a docker service you would like to see?
![image](https://user-images.githubusercontent.com/73854485/127257680-67f3d026-9c3d-45c3-8335-1b7e9829e019.png)

**Comment by PJEstrada** [comment]
Hey @cvm-int ,

This new resync button will not generate sync events as this is more of a "manual" action. The result you should see is that the number of tasks inside this task template should be the same as the number of files on the dataset. This button is more of a "fallback mechanism" in case the sync engine did not work correctly. But with the exception of manual DB queries, the sync engine should always trigger the task creation of new files that go inside the dataset as long as the task template is active.
