### ISSUE TITLE
[Import Wizard] Match on filename in update context

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#180]
Context of request to match on filename not just ID.

I believe right now we enforce unique filename across a dataset. 
And each batch of import needs to target a specific dataset?
So in that context, it seems reasonable to also match on filename.

I think a similar pattern is how we handle the labels. We try first to match on the Diffgram ID,
but if that fails we try to match on label string.

**Comment by PJEstrada** [comment]
Sounds good this looks like a reasonable thing to add, I'll work on this as soon as possible.

**Comment by anthony-sarkis** [comment]
@PJEstrada I believe this is already solved - is it ok to close?

**Comment by PJEstrada** [comment]
Yes we  can close now :) I linked PR for reference
