### ISSUE TITLE
Add Support for Downloading Images of Dataset With Annotations Drawings on them

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#214]
Users sometimes need to provide the images for the annotation with the annotated data already drawn in it in a known format such as jpeg or png.

It would be great if diffgram could offer and option to download the dataset's raw data with the annotations drawn on top of them.

**Comment by anthony-sarkis** [comment]
One option is the existing segmentation mask functions. A delta is I believe they squash the color space to 0-255 grayscale, something similar but using the RGB defined colors could work.

If we put a link to the Diffgram Task in say an export report, then that may reduce the need for this
Also, if we someone link a "reporting slice" to the dataset explorer, that would be a way to explore multiple items in a set quickly.

Even if eventually we offer both I think the link to Diffgram task or query set slice would be better long term becuase then it works the same for all data type (video, audio etc)

**Comment by anthony-sarkis** [comment]
Going to close this as I'm not sure if it's aligned with our vision any more.

Doing this would 
1) break PII items
2) break the data out of Diffgram

It would probably be better instead to offer stronger sharing options within Diffgram infra. At the moment there are already many ways to view and share tasks and data, so closing for now.
