### ISSUE TITLE
Support Report For Downloading counts of labels

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#215]
Users need support for a report where the user can see the counts of labels on each image.

For example:

File ID |  File Name | label_a_count | label_b_count|  etc..

We should integrate this in the existing reporting system.

**Comment by anthony-sarkis** [comment]
Just expanding the example given:

![image](https://user-images.githubusercontent.com/18080164/129080108-0ffae038-7855-47de-8036-5a758dd52a0f.png)
