### ISSUE TITLE
[backlog] Instrumentation - flask catch 400 errors into event system

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#227]
Instrumentation idea

A small idea to help us discover this and other errors, what if we add a
global wrapper on flask routes, that if it's a 400 error it attempts to
create a diffgram event with the log? (or something similar)

That way we have more statistical insight to how often these type of things
are occurring. Plus potentially more information in terms of time stamps
and relevant instance list etc.

Main context is desire to store the diffgram internal log which new relic or other logging I believe doesn't capture
It's also just easier sometimes to have these "named" events instead of having to deduce it from general logs

**Comment by PJEstrada** [comment]
I wanted to add this for further discussion:

https://docs.newrelic.com/docs/telemetry-data-platform/convert-to-metrics/create-metrics-other-data-types/

Newrelic supports building metrics from existing log data, we just create an regex or query to get it and it should seamlessly record them as special metrics.

The only thing with this is users in the opencore context might not get that visibility though.

**Comment by anthony-sarkis** [comment]
that looks cool

> The only thing with this is users in the opencore context might not get that visibility though.

+1 to this being a real blocker

This may be an AND function thing where we wish to provide basics right in Diffgram for super admins, and then have generic "exit" points for advanced users. eg if they want to run diffgram with newrelic, query log data and other stuff in custom ways they desire etc

**Comment by anthony-sarkis** [comment]
closing this in favor of these new tickets
* https://github.com/diffgram/diffgram/issues/1462
* https://github.com/diffgram/diffgram/issues/1141
