### ISSUE TITLE
[backlog] UI experience when multiple instances with same hashable data

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#233]
Context of 
https://github.com/diffgram/diffgram/pull/225
https://github.com/diffgram/diffgram/issues/226

Right now UI does not warn user if they copy and paste instance and then keep it the same. This means the state that gets saved is different from what the UI shows. 

Conceptually this should be a rare case but we should still handle it better

**Comment by anthony-sarkis** [comment]
@PJEstrada  One more - I believe this was was also solved already with the frontend duplicate warning right?

**Comment by PJEstrada** [comment]
Yes you're right! we can now cloase this one
