### ISSUE TITLE
[backlog] Discussion on Lossless formats like TIF/TIFF

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#240]
Workaround example:
https://stackoverflow.com/questions/28870504/converting-tiff-to-jpeg-in-python  

Main contexts here is
1) What do we need to do reasonably render it on frontend
2) Storing the original, in the context of Diffgram being the one database for all of the data.

**I'd like to get more peoples insights into the need for this and desires here.**

one context, material science:
"microscopes provide .tif, which we like as it typically stores the acquisition metadata and pixel information without quality loss."

**Comment by MathijsNL** [comment]
If someone has a usecase where TIFF is used it would be really annoying to convert to a different format and not being able to use the original media in a simple way.

Since we just made the PNG lossless change we could probably apply something similar for TIFF files.
If the file is TIFF just save the facing media as .PNG. This way the orignal TIFF gets uploaded to the cloud, and the facing media in PNG will have a minimal difference in quality for annotations. I am by no means an expert on the TIFF format, but it seems that imageio supports it so converting it to PNG with a compression level of choice wouldn't be hard.

**Comment by anthony-sarkis** [comment]
That sounds reasonable. Good idea!

Continuing to more purposefully separate the raw storage versus the
presentation layer I think is a good idea in general. It helps us make
better trade-offs and gives the user more flexibility.

**Comment by MathijsNL** [comment]
I am running some tests right now with TIFF files, it seems that layered files are giving some problems.

Multi layered TIFF :
![image](https://user-images.githubusercontent.com/1612886/154763635-907f23ec-d12b-410d-be9c-3081ebf0b87e.png)

ImageIO output:
![image](https://user-images.githubusercontent.com/1612886/154763711-72dbf54b-8d89-4eb0-96f7-f08ce3f698e1.png)


I think multi layered TIFF files are out of the scope for what Diffgram should be able to handle, so people will just have to take the TIFF processing as it is, just 1 layer. Maybe it would be nice to have some help text on the upload page with an explanation about the extensions and assumptions so people know what to expect?

It seems like different TIFF settings like compression type etc. don't matter for the output. ImageIO can read it, and will save it as PNG.

**Comment by anthony-sarkis** [comment]
For DICOM and some geospatial stuff we need to build layers support anyway! :) 
Added https://github.com/diffgram/diffgram/issues/637

Given that, it may not be too hard to extend this to TIFF or think about more generic aspects for this. As a low priority I think.

Agree on better docs, perhaps linked from upload page more clearly too. We have:https://diffgram.readme.io/docs/ingest-data
https://diffgram.readme.io/docs/importing-your-data#image-formats


Regarding your eariler note, DICOM, SAR (radar) are two that jump to mind.

We have some sperate tickets going for more general media interfaces, like PDF etc but I think that's out of scope for this image focused discussion.  More generally the challenge is that each format often has some little "gotchas" that can end up cascading into different changes. (even images, EXIF data etc for orientation) 

Let's try this phrasing:
- ImageIO will cast it easily into a JPG or PNG for presentation layer
- Is a single layer
- Requires no interface or product expectation changes

Because if all those are true it would basically be as simple as adding them to the allow list,
and checking it casts it / updates extension correctly I think

**Comment by MathijsNL** [comment]
Thanks for thinking along @anthony-sarkis. 

Allowed extensions for now will become:
```
images_allowed_file_names = [".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"]
```

Extending them will be relatively easy. Let's just see if any issues get posted with request for more image formats.
