### ISSUE TITLE
[backlog] Document, clean, refactor AnnotationUpdate

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#242]
Context that we recently have added a series of validations and improvements.

I want to gather and update existing flow charts and architecture diagrams.

Continue removing stale comments. General refactoring.

I'd especially like to differentiate the 1) expected cases, 2) edge cases, and 3) ultra "DB got corrupted" we are in Antarctica cases.

**Comment by anthony-sarkis** [comment]
Antarctica cases:
1. `detect_and_remove_collisions` (from existing) is one example of something that should only be encountered from DB corruption

Somewhat rare cases:

1. `__identify_and_merge_duplicate_ids()`  ID specific cases, mainly from unexpected frontend or ingestion corruption
2. `detect_special_duplicate_data_cases_from_existing_ids()` description TBD
3. `__check_all_instances_available_in_new_instance_list()` Frontend has lost sync with backend. Should be a fairly rare state if frontend if validating as expected

**Comment by PJEstrada** [comment]
I've shared a new diagram:

![Annotation Update Flow Diagram Aug 2021](https://user-images.githubusercontent.com/6606958/129948193-de6803c3-aca4-4c95-8407-4dbd2703b573.png)

I've added some notes documenting the special cases there :) let me know if you think this is thorough enough, and we can close this one
