### ISSUE TITLE
[backlog] Ingest, Automatic creation of labels -> include attributes

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#253]
In the context of the new Diffgram to Diffgram ingestion.

Realized that in the test project, the automatic label creation just creates the labels and not the attributes too.
Probably expectation is to have complete Schema created.

Gotchas:
The new Attribute IDs will be different from the ones on each instance too, so may need to map that or re-write that in some way in the process.

**Comment by PJEstrada** [comment]
Hey Anthony, this def a thing we need to include. Bother with the export and the normal mapping process eventually.
I will prioritize the export for now to have a complete "dump" of the annotations working seamlessly.

**Comment by anthony-sarkis** [comment]
Thanks Pablo! :)
