### ISSUE TITLE
DIFFGRAM_INSTALL_FINGERPRINT is not Set as an ENV variable.

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#255]
Some users are reporting issue with what appear to be fresh installations - 

User:

Aug 23, 2021, 1:13 PM
> I managed everything to run but when I tried to create a user, an error was returned.

> I did some quick debugging and noticed the default container exited due to the following error:
> 
> [2021-08-20 14:28:05,923] ERROR system_events.py Line 52: DIFFGRAM_INSTALL_FINGERPRINT is not Set as an ENV variable.

(We came across this 2x recently so putting here to track)

**Comment by anthony-sarkis** [comment]
Ok so this new feature is missing on the Docker Compose context https://github.com/diffgram/diffgram/blob/0e874fc9a678dd4b990158d18e2c1bf859405f0e/docker-compose.yaml#L56

Let's document this somewhere so our standard process is to always add these new env vars there too, I'll work on this now

**Comment by anthony-sarkis** [comment]
Fixed here https://github.com/diffgram/diffgram/pull/256
Note must do `docker-compose up -d` to fix existing install

**Comment by anthony-sarkis** [comment]
@PJEstrada I'll await your verification on this and the hotfix pull request before closing this

**Comment by PJEstrada** [comment]
Hey @anthony-sarkis, thanks for catching and handling this one. The code looks good for me so I think we can close this one if you're ok with it :)

**Comment by anthony-sarkis** [comment]
Ok sounds good!
