### ISSUE TITLE
Change The DB Creation to use Alembic in the Testing context.

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#30]
We are still using the setup_supporting.py to create the tables on unit tests and e2e tests. We need to call alembic here to be consistent with the schema on both contexts and get schema error during unit tests if there are any problems with alembic.

**Comment by PJEstrada** [comment]
For reference, this is what we can use to hook alembic inside a python script without invoking shell commands: https://stackoverflow.com/questions/24622170/using-alembic-api-from-inside-application-code

**Comment by anthony-sarkis** [comment]
Super!!
