### ISSUE TITLE
'Project' object has no attribute 'client'

### ISSUE THREAD

**Issue by aniketzz** [diffgram/diffgram#305]
I am using diffgram version 0.4.15. While running the `project.get_label_file_dict(use_session = False)` code I am getting  `AttributeError: 'Project' object has no attribute 'client'` error. 
![image](https://user-images.githubusercontent.com/23217704/134675628-acea9666-97f1-4752-a721-6e18160d62d8.png)

**Comment by PJEstrada** [comment]
Hi @aniketzz,

This was a confirmed bug, thanks a lot for sharing. It has been fixed in version `0.4.17`. Can you can try doing:

`pip install diffgram==0.4.17`

That should fix your issue :)

I will close this for now, but if you keep having the issue feel free to re open or open a new issue.
