### ISSUE TITLE
ImportError: cannot import name 'get_coco_api_from_dataset' from 'coco_utils'

### ISSUE THREAD

**Issue by Shantam07** [diffgram/diffgram#306]
![Screenshot (107)](https://user-images.githubusercontent.com/75930279/135030655-779717dd-78de-4063-bf75-bc77b0b08706.png)

While trying to run my file I am getting this error  --  cannot import name 'get_coco_api_from_dataset' from 'coco_utils'

**Comment by PJEstrada** [comment]
Hello @Shantam07,

Thanks for trying diffgram out :) Can you please share the code you are running and also share if you are using the diffgram SDK or trying to setup a local diffgram installation?

**Comment by Shantam07** [comment]
``
[dddd.zip](https://github.com/diffgram/diffgram/files/7245670/dddd.zip)

**Comment by anthony-sarkis** [comment]
@Shantam07 
engine.py is not part of diffgram. 
please check your code.
closing for now please reopen if above is wrong

<br>

![image](https://user-images.githubusercontent.com/18080164/135154851-c3a07b0f-42f6-4d9a-892d-a4a686995c97.png)
