### ISSUE TITLE
Curve Quadratic is crashing around calculate_min_max_points 

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#388]
Instance type curve quadratic is crashing with
```
vue.esm.js?a026:1897 TypeError: Cannot read properties of undefined (reading 'x')
    at VueComponent.calculate_min_max_points (annotation_core.vue?d2b4:4715)
    at VueComponent.current_instance (annotation_core.vue?d2b4:1817)
```

To reproduce attempt to create a quadratic curve type
good chance to add tests for this type if we don't have them already

**Comment by anthony-sarkis** [comment]
Also needs tests

**Comment by anthony-sarkis** [comment]
@PJEstrada  suggesting if you want this one becuase I believe you know most about this part of system

**Comment by PJEstrada** [comment]
Thanks Anthony! Will fix it and add tests on https://github.com/diffgram/diffgram/pull/679
