### ISSUE TITLE
Add a Task Completion Dialog Before Completing a Task in Review Mode

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#419]
When the task template has the review mode activated:

- When a user completes a task, and the task in `in_progress` status. Before actually completing the task, we need to ask in a popup dialog, who should review this task.
- We can also think of ways of automating the review assignation at the task template wizard level, so annotator don't have to choose who reviews their task. In this case maybe adding support for being able to select a default reviewer or reviewers, so then the system automates the assignation of the reviewer when the task is completed. This one might require a bit of more backend support, but the first bullet I think could be fully supported once the features on https://github.com/diffgram/diffgram/pull/406 are merged.

When Already in Review:
- When the reviewer completes the task that is `in_review` status. We open another popup dialog before completion, asking if the reviewer wants to approve the review (Which should complete the task). Or request changes to it. Which should set the status to `requires_changes`. These feature is supported on the backend already via the endpoint `/api/v1/task/<int:task_id>/review`

**Comment by vitalii-bulyzhyn** [comment]
Lemme clarify few details:

- This dialog should only be active only if the reviews enabled for the job, right?
- If the reviewer already assigned to the task, should it be dialog or not?
- When it asks for assigning reviewer, in this field should be only available users who were added to the job as reviewers, right?
- When the task require changes, do we need to supply some kind of message along with changing status?

**Comment by PJEstrada** [comment]
Hey Vitalii:

1. Right, this one should only show up when the `job.allow_reviews` is true. And the status is that the review is in progress.
2. Yes, it should show it when the reviewer hits the "complete" button. In this case the button should be a "Complete review" button instead of a "Complete task" button. So it should show only if the reviewer is assigned, other users should not be able to add reviews unless added as reviewers.
3. For the reviewer selection, I think we can remove that as now the system is assigning the reviewer automatically. The dialog should just show an approve/reject button, and a text field to add some comments to it. You don't have to worry about the reviewer selection as the system will assign it automatically to the reviewer with less tasks assigned at the current moment.
4. Yes, we can provide a text comment box on the status. You can see the `discussion_comment_new.vue` component to see the current text box we have for comments. Also the `/api/v1/task/<int:task_id>/review` Url accepts the `comment` key on the payload to send the text there.
