### ISSUE TITLE
[media processing direction] Make Processing Concepts more Flexible

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#423]
We do a variety of pre-processing that can sometimes be a bit heavy. eg pulling frames out in video, etc.
I'd like to make this more flexible. So cases where this is needed we have it, but it's not an all or nothing forced thing.
For example for images, our storage options are good, but in some cases perhaps allowing users to simply provide a URL is also an option.

**Comment by PJEstrada** [comment]
This one is a really good idea Anthony. I think this would allow us to support things like using an existing bucket, without having to copy the files. And would also reduce the RAM need of huge videos if we need to speed up the data uploading.

**Comment by anthony-sarkis** [comment]
This was somewhat addressed with "by reference" add-ons.
Some of this is targeted in the 2.0 refactor.
This specific ticket is a little too general / stale so closing it.
