### ISSUE TITLE
Display Current Status Of Task In Annotation UI

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#430]
### Rough UI Idea:

![image](https://user-images.githubusercontent.com/6606958/140980266-2fdcb553-6c05-46ca-804d-cdb65a92dec4.png)

### Main Purpose of the Feautre:
- Make the user aware of the stage the task is at. 

### Notes:
Maybe a good use case for the timeline component (horizontal timeline): https://vuetifyjs.com/en/components/timelines/#small

### [For Reference] Current Available Statuses:

```
TASK_STATUSES = {
    'created': 'created',
    'complete': 'complete',
    'in_progress': 'in_progress',
    'review_requested': 'review_requested',
    'in_review': 'in_review',
    'requires_changes': 'requires_changes',
    'deferred': 'deferred',
}

```

### [For Reference] General Idea of Status Flow:

![image](https://user-images.githubusercontent.com/6606958/140981152-a4903f57-1893-4c33-addd-478f265c636f.png)

### [For Reference] Some more UI Components Ideas:

![image](https://user-images.githubusercontent.com/6606958/140980985-43e94050-c142-4e4b-9655-2117a632c636.png)

**Comment by vitalii-bulyzhyn** [comment]
@PJEstrada about this task. Where do you think will be the best place to fit this? Our toolbar if already quite crowded with other stuff

**Comment by PJEstrada** [comment]
Agreeing to add a single icon to the toolbar with the curren status. The when hovering that icon, we can see the entrie timeline of the task.
