### ISSUE TITLE
Duplicate calls in Studio or Task Context

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#431]
Loading the studio appears to result in duplicate calls to 
1. `file/list`.
2. label refresh

This delays the first time load experience, and generally isn't good.
Likely this is a regression.

![image](https://user-images.githubusercontent.com/18080164/141026119-56688289-6928-44e1-8ad2-9b886ee65ebe.png)

![image](https://user-images.githubusercontent.com/18080164/141025765-92a4dd28-bc22-4f58-9a88-e468c069c767.png)

There is also a duplicate call for annotations but that's only a cascade from file list.

**Comment by anthony-sarkis** [comment]
@PJEstrada has already solved some of these and maybe we can link PR for new ones

**Comment by PJEstrada** [comment]
Fixed on 1.11.2
