### ISSUE TITLE
Azure connection read test fails in setup.py

### ISSUE THREAD

**Issue by tkupek** [diffgram/diffgram#444]
I'm trying to setup diffgram with the provided `setup.py` script.

I have created an Azure storage with the container and respective access rights, but when I insert the _Connection String_ into the `setup.py` it fails with:

```
Please provide the Azure Container Name [Default is diffgram-storage]:
Testing Connection...
[OK] Connection To Azure Account
[OK] Write Permissions
[ERROR] Read Permissions
Error Connecting to Azure: Please check you have read permissions on the Azure container.
Details: Traceback (most recent call last):
  File "install.py", line 143, in validate_azure_connection
    account_key = client.credential.account_key
AttributeError: 'NoneType' object has no attribute 'account_key'
```

The code where it fails looks like this:

```python
client = BlobServiceClient.from_connection_string(connection_string)
...
shared_access_signature = BlobSharedAccessSignature(
                account_name = client.account_name,
                account_key = client.credential.account_key
)
```

This makes little sense to me, as the connection_string already includes a SharedAccessSignature that can be used for reading the storage.

**Suggestion**: Use `blob_client.download_blob()` method to download the test file.

When skipping the test, the installation works.

**Comment by tkupek** [comment]
It seems the same logic is used in `data_tools_core_azure.py`, wherefore the upload to Azure is failing for me if I use

`project.file.from_local`

interestingly,

`project.file.from_url` is working.

**Comment by PJEstrada** [comment]
Hey @tkupek,

Thanks for sharing this issue. I just tried the install script with one of our test connection string and the connection tests seems to be good. The code that is failing seems to be related to the azure SDK for python. 

So I wanted to ask what version of the azure python sdk do you have right now?

**Comment by tkupek** [comment]
Thanks for the quick response.

I have these packages installed:
```
azure-core               1.20.1
azure-storage-blob       12.8.1
```
as, defined in the `requirements.txt`

**Comment by PJEstrada** [comment]
Thanks @tkupek ,

I think this might have something to do with the connection string format. I think azure has different ways of showing this. Would you be able to share your connection string (without the keys). Just to compare that.

What we use as connection string format is similar to this:

`DefaultEndpointsProtocol=https;AccountName=theaccountname;AccountKey=a_long_account_key==;EndpointSuffix=core.windows.net`

Is your connection string in a similar format?

**Comment by tkupek** [comment]
@PJEstrada thank you, that was it.

Azure is confusing here, because they also have a "connection string" in the Shared access signature section:
![image](https://user-images.githubusercontent.com/4039384/142226640-667709b2-a600-4a06-ac71-b94c7c2f1f9d.png)

**Comment by PJEstrada** [comment]
Great glad it's working!Yes you're right. It can be a bit confusing to determine which one is it. We will try to show more meaningful errors in the future though to guide users with similar issues.

**Comment by tkupek** [comment]
Great support. Thanks
