### ISSUE TITLE
Add More Visbility to the File Name & ID in the system

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#447]
When debugging scripts with the SDK, it can be hard for users to know which files where uploaded and which files they are seeing. Right now the only way to see the file name and file ID is to click the file and then go to the file information section in the editor.

It would be usefult to have it in the following places:

The file preview section:

![image](https://user-images.githubusercontent.com/6606958/142881053-f6dd26be-a593-49b3-9454-e5a41730ff5e.png)

The task list section:

![image](https://user-images.githubusercontent.com/6606958/142881129-d2700f92-ecc3-4f05-b6b1-ba4915625616.png)

Maybe: in the top navigation bar of the annotation editor so users can easily see what file they are viewing (add something liek Name + File ID)

**Comment by anthony-sarkis** [comment]
The fileID will show up in the query param in the URL.
![image](https://github.com/diffgram/diffgram/assets/18080164/4f6d6545-897e-4a87-bd84-48c9aa2b002e)


On Tasks, there is an ID column that can be added 

![image](https://github.com/diffgram/diffgram/assets/18080164/83b59a24-2bd6-4cfd-bdee-e739adae5d18)
![image](https://github.com/diffgram/diffgram/assets/18080164/3c6e3408-72c9-446d-8d58-05205d3b6354)
