### ISSUE TITLE
DIP 1: Support for Text Interface

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#452]
# Metadata

- DIP Number: 1
- Author: Pablo Estrada
- Title: UI For Text Annotation
- Description: Develop V1 For Text Labeling Interface
- Implementation Assignees: Vitalii Bulyzhyn & Pablo Estrada

# Abstract 

New users are requiring annotations for text files mainly for NLP purposes. Diffgram has currently no UI for supporting this. Adding a text interface will allow more users to get the benefits of Diffgram's data management existing features, and data ingestion features while expanding the number of use cases where Diffgram can be a supporting tool for the training data generation.

Develop an ADR: https://github.com/joelparkerhenderson/architecture-decision-record, initial implementation goals
and actual code for supporting V1 of a text annotation interface. This might include component architecture, stack choice, user stories support, and any other useful information for getting the context of the state of the art in annotation tools.

# Motivation (Rationale):
Help the community of users that work in the NLP space by providing an integrated platform for text annotation training along with all the other benefits in the 9 core pillars of the Diffgram platform.

# Specifics 
Some of the core goals for this improvement
- Product Research
- Initial architectural decisions for frontend
- Some of the backend architecture is already supported, we just need to identify if there are other missing gaps. Specailly in the support of multiple types of NLP annotation styles (Named Entity Relationship, Questions about documents, etc)
- Identify if there are requirements for any extra steps / configurations in the task template wizard or in the label editor settings.
- Define the end goals, development tasks, and user stories to cover for V1 of this Text interface.

# Notes & Considerations
Main focus on frontend as most of the backend architecture will already support ingestion and annotation storage.
Reference for DIPs: https://diffgram.readme.io/docs/diffgram-improvement-proposals-dip-reference

**Comment by anthony-sarkis** [comment]
V1 was shipped!!
