### ISSUE TITLE
Deploy from branch appears to have an issue (deploy from tag works fine)

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#454]
Work around is to just deploy from tag
https://github.com/diffgram/diffgram/runs/4374811739?check_suite_focus=true

maybe an env variable or something?

![image](https://user-images.githubusercontent.com/18080164/144153567-6146ec2c-3fc3-48c6-bff3-51960eecd0a4.png)

**Comment by PJEstrada** [comment]
Thanks Anthony I'll check it out now!

**Comment by PJEstrada** [comment]
Closing since there's duplicate here: https://github.com/diffgram/diffgram/issues/666
