### ISSUE TITLE
Investigate times when instance frontend validation fails

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#490]
### Problem
We are getting a relatively high volume of hits for `__check_all_instances_available_in_new_instance_list` which may indicate the frontend is sending invalid states to the backend.

Solving this would also likely help with that concern on saving, but putting this as a seperate ticket since it's more on investigation work side.

Most likely this is from some kind of rapid state changing that needs to be better controlled on the frontend.

### note from other ticket
(Pablo) Maybe we can explore a bit more how are you getting the buttons smashing to eventually lead to the issue so we can analyze the root cause and missing blocks on the frontend? Also it seems that we might be able to replicate it

https://github.com/diffgram/diffgram/pull/489#issuecomment-1004901098

Code block
https://github.com/diffgram/diffgram/blob/61e34c951209e97ac10537f101d279616a2173cb/shared/annotation.py#L440

### frontend context from chat
I think if this can be tackled on the front end that would be best
becuase the backend we are having to intuit , or block etc
but on the frontend we can really add a bunch of controls to ensure the smooth flow 

(Agreed)

Right becuase the user should never be able to jam a button that will break it
I feel like we disable a bunch of things already, but maybe just a fresh look at really saying "ok we expect them to try to change frames the moment they save, or to jump between with other thing, etc. etc" and just at every step check the loading, even if it means some duplication
sort of like a defense in depth thing instead of golden path assumptions

**Comment by PJEstrada** [comment]
Idea from chat:

Investigate if the `add_ids_to_new_instances_and_delete_old` is being called on the right frame during saving and changing frames.
