### ISSUE TITLE
Fix a Flaky Test: Unassign users to multiple tasks

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#554]
This test is making it look like CI fails at quick glance when rest are all passing.

https://dashboard.cypress.io/projects/djxpvm/runs/3045/test-results/885230a9-1011-4491-8c59-aa2a4fceb4e4?utm_source=github&isFlaky=%5B%7B%22value%22%3Atrue%2C%22label%22%3A%22Flaky%22%7D%5D

It seems to be only one that's a medium
https://dashboard.cypress.io/projects/djxpvm/analytics/flaky-tests

**Comment by PJEstrada** [comment]
This was fixed on  #553 the flaky tests was due to a task template not always being available. We now added a new command to create task templates on demand before running test: https://github.com/diffgram/diffgram/pull/553/commits/8a21d97f7ce1309c9ef4b249e70e84aedb3a2eb0

**Comment by anthony-sarkis** [comment]
Awesome!
