### ISSUE TITLE
Prevent duplicate assignments

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#569]
We added ability for `n` users to be on same task.
But if the system auto assigns a user, and then that user is manually assigned, it shows up as a duplicate.
Desired state is to prevent duplicates here.

![image](https://user-images.githubusercontent.com/18080164/152608504-7769d263-f461-42ba-85a4-1b0da9bf8361.png)

**Comment by PJEstrada** [comment]
This should be fixed on the Exams PR:

We added the existing relation check to prevent duplicates:

```
    def add_assignee(self, session, user):
        existing_rel = TaskUser.get(session, user.id, self.id, 'assignee')
        if existing_rel:
            return existing_rel
        self.assignee_user = user
        rel = TaskUser.new(
            session = session,
            user_id = user.id,
            task_id = self.id,
            relation = 'assignee'
        )
        user.last_task = self
        return rel
```

I'm going to close this one for now, but if it still persists we can re open it. I already tried on latest master and issue seems to be gone.
