### ISSUE TITLE
HIPAA Compliance

### ISSUE THREAD

**Issue by RAbraham** [diffgram/diffgram#579]
Hi,
If we install Diffgram locally on a private server with access to S3, is diffgram HIPAA compliant?

https://en.wikipedia.org/wiki/Health_Insurance_Portability_and_Accountability_Act

**Comment by PJEstrada** [comment]
Hi @RAbraham 

I'm not HIPAA compliance expert. The only thing I can tell you is that Diffgram does not store any data from your S3 files on its DB. We only store signed URL's to the data. The actual raw files always stay on the blob storage backend (either aws, gpc or azure). So if you install diffgram on a private server, this private server will only have access to the files via the signed URLs. The private server will never store any of the files on its file system

**Comment by RAbraham** [comment]
Hi @PJEstrada 
Thank you very much for that quick answer.
- I think even if diffgram on the private server has access to those URLs, it's the responsibility of the private server(that means, us :) ) , not to get hacked. So that sounds good.
- Since they are presigned urls, I think that means anyone can access them without creds. If Diffgram is installed on a private server, do these presigned urls leave that private server at any point? for e.g. usage metrics that you may collect for feature development. I think the answer is no, but sorry I have to ask :(. It's part of a check.

**Comment by PJEstrada** [comment]
At this current point there should not be any signed urls being sent out of the diffgram server. Not even as metrics, so I think we should be good with that too :)

**Comment by RAbraham** [comment]
That's great. Thanks!
