### ISSUE TITLE
Postgres permission errors with local db on Linux (Centos)

### ISSUE THREAD

**Issue by MathijsNL** [diffgram/diffgram#580]
Using diffgram 0.11.15 works flawless under windows when running python install.py and after entering all the required info.

On Linux Centos 7 the following error appears:
docker logs diffgram_db_1
chmod: changing permissions of '/var/lib/postgresql/data': Permission denied
chown: changing ownership of '/var/lib/postgresql/data': Permission denied

python install.py is run as root, anything I am missing here?

**Comment by PJEstrada** [comment]
Hi @MathijsNL,

`install.py` eventually runs `docker-compose up`. Can you please check the permissions of the dir `/var/lib/postgresql/data` and maybe try to run `docker-compose up` with `sudo`?
