### ISSUE TITLE
Using external postgres database fails under Linux

### ISSUE THREAD

**Issue by MathijsNL** [diffgram/diffgram#582]
Hi there,

When using diffgram 0.11.15 with a remote postgres database everything works fine under windows.

Under Linux (Centos 7) there seems to be a problem with the database connection. During the python install.py the database connection seems to be successful, but in the diffgram_default_1 container it shows the following errors:

**docker logs diffgram_default_1**
psql: could not translate host name "db" to address: Name or service not known
Postgres is unavailable - sleeping
psql: could not translate host name "db" to address: Name or service not known
Postgres is unavailable - sleeping
psql: could not connect to server: No route to host
        Is the server running on host "db" (172.X.X.X) and accepting

I haven't found where the host name "db" gets defined so I can't fix it right now.  I also have no clue why it tries to connect to a 172.X.X.X IP as I haven't filled that in anywhere.

Hopefully someone can point me in the right direction.

**Comment by MathijsNL** [comment]
To get this issue a bit more clear, I got it sort of working by butchering the https://github.com/diffgram/diffgram/blob/5d2d4e3/default/db-init.sh file.

```
#!/bin/sh
# db-init.sh

set -e

host="$1"
shift
cmd="$@"

PGPASSWORD=MySecurePassword psql -h "X.X.X.X" -U "postgres" -c '\q';

cd shared; alembic upgrade head
exec $cmd
```

So somewhere the host (and maybe even password) for the external db doesn't arrive to the diffgram_default_1 container.

**Comment by PJEstrada** [comment]
Hi @MathijsNL,

Good catch on this one!

I think what we can do for this is just replace the `"db"` string on the command to the ENV variable that includes only the postgres host. 

To do this I think these ideas can work:

1. On the `install.py` script. We can modify the function:
```
    def database_config(self):
        local_database = bcolors.inputcolor(
            'Do you want to use the local database? Y/N [Press Enter to use Local DB]: ')
        local_database = local_database.lower()
        if local_database == 'y' or local_database == '':
            self.local_database = True
        else:
            self.local_database = False
            valid = False
            while not valid:
                database_url = bcolors.inputcolor(
                    '\n\n >> Please enter the Remote Postgres Database URL\n    NOTE: The syntax for URL is: "postgresql+psycopg2://<db_username>:<db_pass>@/<db_name>?host=<db_host>": ',
                    bcolors.OKBLUE)

                bcolors.printcolor('Testing DB Connection...', bcolors.WARNING)
                try:
                    # Testing connection
                    engine = create_engine(database_url)
                    conn = engine.connect()
                    conn.close()
                    valid = True
                    self.database_url = database_url
                    bcolors.printcolor('✓ DB connection succesful!', bcolors.OKGREEN)
                    time.sleep(2)
                except Exception as e:
                    bcolors.printcolor(
                        'Connection test failed: Please check that your DB URL has the correct values and try again.',
                        bcolors.FAIL)
                    bcolors.printcolor('Error data: {}'.format(str(e)), bcolors.FAIL)
                    valid = False
```

So that we can extract the host_name from the `self.database_url` and save it on a new attribute `self.db_host`.

Then on the  `populate_env()` function in `install.py` we can add a new line similar to this:

`            env_file += 'DATABASE_HOST={}\n'.format(self.db_host)`

This would allow us to have the host on a separate env variable.

We can the just reference this on the command like this:
`
command: ["/app/db-init.sh", ${DATABASE_HOST} "python3", "-u", "/app/main.py"]`

I'm not quire sure if we have to add the double quotes or not to the env variable reference but the would be the main idea.

Let me know your thoughts on this

**Comment by MathijsNL** [comment]
Hey @PJEstrada,

Nice ideas there.

I was thinking of asking for a few more questions if you choose external DB instead of the connection url.

- db_username
- db_pass
- db_name
- db_host

Then it is very simple to create the database url:
```
database_url  = f"postgresql+psycopg2://{db_username}:{db_pass}@/{db_name}?host={db_host}"
```
The variables will be separated from the start, and the env variables can be set accordingly. Escaping passwords might be something to look into as well to make sure it always works.

**Comment by PJEstrada** [comment]
Sure those are great ideas too,

For the URL I think there might be 2 types of syntax for it. I've seen users also use this:

`connector + "://" + db_username + ":" + db_pass + "@" + db_host + "/" + db_name`

I'm not completely sure if they are equivalent or not but I think we can try both and see if the system behave correctly.
