### ISSUE TITLE
Connection to Private File System

### ISSUE THREAD

**Issue by RAbraham** [diffgram/diffgram#583]
Hi,
I see that one can only upload from S3/Google Cloud Storage or images from my personal machine?

We run diffgram on a private server for now and we also have our raw data initially on the same private server. Is it possible to make a connection to the path which contains our raw data on the private server? For e.g. edit the docker-compose file and mount our raw data folder and make it visible on the UI in some way for our labeler to import images from? or any other way. I guess we could push to a S3 bucket but just curious if this was possible.

**Comment by PJEstrada** [comment]
Hi @RAbraham,

For now we don't support out of the box local storage mounting. 

We have an open issue for that: https://github.com/diffgram/diffgram/issues/310

However you could look into https://min.io/ I think they allow you to bind local file systems and access them through the S3's API. 

If that's true, in theory you should be able to set it up as an S3 connection. Although in the future we would like to add native support for local filesystems or MinIO

For now I'm going to close this one and point it too the original issue to continue any discussions on this: https://github.com/diffgram/diffgram/issues/310

**Comment by RAbraham** [comment]
sounds good. thanks
