### ISSUE TITLE
tests issue after merge

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#61]
It was showing as passing here: https://github.com/diffgram/diffgram/pull/53
But then when merged to master now shows as failing
I'm not sure what happened- could I get your help please Pablo

**Comment by PJEstrada** [comment]
I see. It seems that the E2E tests failed here. I suspect we might have some flaky tests: https://dashboard.cypress.io/projects/djxpvm/runs/854/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&utm_source=github

**Comment by PJEstrada** [comment]
It seems that this could be that our test runners still are underpowered, since in the dashboard the video freezes. There is a known issue about this: https://github.com/cypress-io/cypress/issues/8210

I will double check the resources of the azure runners to see if this is the problem.

**Comment by anthony-sarkis** [comment]
Thanks @PJEstrada
