### ISSUE TITLE
Dissapearing annotations

### ISSUE THREAD

**Issue by Emmanuel-Messulam** [diffgram/diffgram#622]
After annotating with either bounding box or polygonal segmentation, sometimes the annotation dissapears.

**Comment by anthony-sarkis** [comment]
Can you please provide a screencast video or screenshots?

Are there any specific annotation features being used? (eg autoborder)

There are a variety of features that hide annotations (focus mode, layers
etc) , can you double check that none of those are active?

**Comment by anthony-sarkis** [comment]
Closing inactive - please reopen when you have more information
