### ISSUE TITLE
Python coding style choices

### ISSUE THREAD

**Issue by MathijsNL** [diffgram/diffgram#632]
There are a lot of different coding styles used within Diffgram.

- String concatenation
- .format strings

Python f-strings are not used at all except for one instance in the install.py script.

In my opinion f-strings are more readable. For people that don't know enough about this topic I will illustrate this with a simple example.

```python
# String with .format
subject = "[{}]{} Has Shared an Instance With You ".format(self.project_string_id, self.user_sending.first_name)

# F-String

subject = f"[{self.project_string_id}]{self.user_sending.first_name} Has Shared an Instance With You "

```

@PJEstrada if you agree I can do the conversion. Let me know

**Comment by PJEstrada** [comment]
Hey @MathijsNL,

Yes I would like to see more F strings in the project as we progress, I agree they are more readable.

Same idea with vue js and using backticks instead of string concat.

@anthony-sarkis  can also give us some pointers on his opinions on this

**Comment by anthony-sarkis** [comment]
Sounds good to me!
