### ISSUE TITLE
Exam List: TypeError: ('profile_image_thumb_url')

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#656]
Test project https://diffgram.com/foulscowl/exam/3099

````
TypeError: Cannot read properties of undefined (reading 'profile_image_thumb_url')
````

I suspect this is something with the user profile image and not the actual exam component, it's just where it happens to show up
Exam list api itself is 200 OK

**Comment by PJEstrada** [comment]
This was fixed on previous release. Closing for now :)
