### ISSUE TITLE
Unreachable http://127.0.0.1:8085/ | diffgram-dispatcher-1 is failing to run 

### ISSUE THREAD

**Issue by wolframalpha** [diffgram/diffgram#685]
I followed the mentioned installation method the install.py was executed successfully. 
But Web UI @ http://localhost:8085/ is unreachable. 

I checked the running containers, diffgram-dispatcher-1 exited, and below is the error:

![image](https://user-images.githubusercontent.com/12759375/155981749-3b907bd7-c3e5-4650-a338-3bc0c53bafab.png)

Below is the snapshot of all the Docker containers:
![image](https://user-images.githubusercontent.com/12759375/155982069-8a1c3fc9-0427-4a5c-85b2-aaf1deaa4bd8.png)

**Comment by PJEstrada** [comment]
Hi @wolframalpha,

We have created a fix that will be released on next version here: https://github.com/diffgram/diffgram/pull/687

We will release this as soon as possible 

Thanks for sharing this with us :)
