### ISSUE TITLE
 cocoSsd issue  - Userscript

### ISSUE THREAD

**Issue by amrlafi** [diffgram/diffgram#72]
In the [object detection example](https://diffgram.readme.io/docs/object-detection-userscript), as well as in my local development environment the script throws the following exception: `Error: Cannot find TensorFlow.js. If you are using a <script> tag, please also include @tensorflow/tfjs on the page before using this model.`

**Comment by anthony-sarkis** [comment]
### Workaround
As a temporary workaround, we can add the opencv script in the middle
Please advise how well that workaround works for you?
<br>

https://diffgram.readme.io/docs/object-detection-userscript#npm-packages
![image](https://user-images.githubusercontent.com/18080164/119562093-ced98400-bd5a-11eb-9b81-6a4ddd734519.png)


### Issue

This is likely a timing issue. The intent is that `add_script()` will only resolve upon `onload` firing:
https://github.com/diffgram/diffgram/blob/1ce8aa3d585b78dabc8b493cbc7d640dff479f4a/frontend/src/components/annotation/userscript/userscript.ts#L468

But it appears that despite that guard, tjfs has not fully loaded before cocoSSD starts loading.
While this issue appears to occur when a model run is attempted, I suspect cocoSSD trys to load on initial download and maybe it's silently failing.

Ideally, I'd like to have a better option here.
I'm not sure what other property we can check other then `onload`? 

Any ideas folks have or want to chime in would be great! :)

**Comment by anthony-sarkis** [comment]
https://github.com/diffgram/diffgram/pull/73
I believe this is fixed here, more information on pull request.
Short story is turned out to be a higher level function firing twice which prevented the onload() promise from working as expected.

**Comment by anthony-sarkis** [comment]
@amrlafi   This is now live  - please feel free to try it on diffgram.com or update from this release https://github.com/diffgram/diffgram/releases/tag/beta-0.4.2
 and see if you are still encountering it?
