### ISSUE TITLE
Add Project Migrator Tool

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#744]
Add tool to be able to migrate projects from external connections such as labelbox, v7, etc.

For this V1 we will start with labelbox’s support only.

**Comment by MathijsNL** [comment]
Is it good enough to be able to import the JSON export from Labelbox?

**Comment by PJEstrada** [comment]
> Is it good enough to be able to import the JSON export from Labelbox?

That could be an option too. Right now we are focusing on using our connections feature to build a better experience without having to generate JSON files. This also helps for really big projects where the JSON files can become to big.

But def a second iteration on this can be adding support for JSON export from labelbox, and other standard formats like COCO, etc..

**Comment by anthony-sarkis** [comment]
@MathijsNL we are building a wizard. so you will be able to put in API key, and then select which projects to import. This way we can bring all data accessible via API (like Project names, users, schema, completion status etc) not just annotations.  Basically making it a "one touch" switch.
