### ISSUE TITLE
docker-compose up: Issue starting PostgreSQL

### ISSUE THREAD

**Issue by r19865** [diffgram/diffgram#810]
Hi, I'm using an Ubuntu machine for my Diffgram.
I've successfully been able to run Diffgram on my machine before, but the other day I got the following error when I ran "docker-compose up".
"PostgreSQL Database directory appears to contain a database: Skipping initialization"
"PANIC: could not locate a valid checkpoint record"

Please let me know what I can do to resolve this issue.

**Comment by MathijsNL** [comment]
@r19865 Are you using the Postgres docker or an external Postgres DB?

**Comment by r19865** [comment]
I’m using the Postgres docker

**Comment by MathijsNL** [comment]
You could just remove the postgres docker container and image, and then run docker compose up -d again. This will recreate it.

Also as @PJEstrada mentioned, this method is not recommended for production environments.
If you really want to use the docker images, I can recommend to use a cloud based SQL service so you have reliable backups of your data.

**Comment by r19865** [comment]
Thank you! I will try this.
