### ISSUE TITLE
Not able to find users in the assign users drop down in task lists

### ISSUE THREAD

**Issue by shivafromdiffgram** [diffgram/diffgram#816]
As detailed in the video, I have a total of 5 users in my project and as an admin user, I should ideally be able to assign certain tasks to users. When I click on manage assignees to select a particular assignee, I cannot do that.

https://www.loom.com/share/fef3e712a74a446ea2b783be0156c99f

**Comment by shivafromdiffgram** [comment]
Hey Pablo @PJEstrada 

Yes the users are added. Sharing another video

https://www.loom.com/share/2214344e2ae24c68b036de5e2c7da373

**Comment by PJEstrada** [comment]
Added fix for this issue now, should be corrected on next release :)
