### ISSUE TITLE
Dataset Explorer: filter by annotations

### ISSUE THREAD

**Issue by inspectorG4dget** [diffgram/diffgram#847]
The dataset explorer currently allows the user to filter by label. However, it does not allow the user to filter by annotations of the images/videos in the dataset. This would be a very useful feature to have

**Comment by anthony-sarkis** [comment]
Already exists! :)
Here `potted_plant` is the label
![image](https://user-images.githubusercontent.com/18080164/167192440-eaee4043-8811-4cba-b8a6-962591af3ae3.png)


If I misunderstood, or there's wording that would make this more clear in docs etc please reopen

**Comment by inspectorG4dget** [comment]
In this example, does `labels.potted_plant` refer to a polygonal annotation of potted plants within each image?

**Comment by anthony-sarkis** [comment]
In this example it refers to the annotation. 
Each annotation is associated with a `label_file_id` that maps to `potted_plant`

The label selector, in image annotation, is used to show the current default label for new annotations

The type of annotation should not matter for this case, although that could be a separate filter

**Comment by inspectorG4dget** [comment]
This is most helpful to know. From a UX perspective though, I find it confusing that `label` means two separate things in different parts of the product. Any chance we can change the filter syntax to `annotations.potted_plant`?

**Comment by inspectorG4dget** [comment]
Aha! I mischaracterized the issue. Labels are "annotations", but Globals are not annotations and I am unable to filter by globals
