### ISSUE TITLE
Default Storage Provider: Consider adding minio to docker compose

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#862]
**Update** We are working on this in Sept 2022

Example
Idea credit: @ppolxda @towr

https://github.com/diffgram/diffgram/commit/d637d2f974b74a8f746e4eb2149c383b0ccae7b5

Also
https://github.com/diffgram/diffgram/commit/9608e58d1324ad4f0a1ff90ece4bfe2368b7adfe

```
minio:
    image: minio/minio
    environment:
      <<: *diffgram-common-env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ${MINIO_DATA_DIR:-minio-data}:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      <<: *diffgram-common-env
    entrypoint: >
      /bin/sh -c " 
      echo $${DIFFGRAM_S3_BUCKET_NAME}; 
      echo $${ML__DIFFGRAM_S3_BUCKET_NAME}; 
      /usr/bin/mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER}  $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/$${DIFFGRAM_S3_BUCKET_NAME}; 
      /usr/bin/mc mb myminio/$${ML__DIFFGRAM_S3_BUCKET_NAME}; 
      exit 0; "
```

**Comment by PJEstrada** [comment]
That's a great idea Anthony! That would remove the need for users to know about MinIO, it can be a default thing for dev environments to better support a "No config" installation

**Comment by anthony-sarkis** [comment]
Thanks Pablo! Credit to @ppolxda

**Comment by khronimo** [comment]
I would really love to see this, or even a better guide on how to set diagram up to run locally or in a vm.

**Comment by vitalii-bulyzhyn** [comment]
Hey @khronimo

We already have it, [here](https://diffgram.readme.io/docs) is our getting started guide [here](https://diffgram.readme.io/docs/minio) is guide how to configure Minio

**Comment by anthony-sarkis** [comment]
**Update** We are working on this in Sept 2022

**Comment by anthony-sarkis** [comment]
Merged https://github.com/diffgram/diffgram/pull/1127
