### ISSUE TITLE
End to end test triggers

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#893]
It appears the end to end (cypress) tests run only when a pull request is first converted from draft to ready for review
but then if there are changes, or say the merge to master etc the e2e tests don't appear to run

(I think maybe already awareness on this but just putting here for tracking)

**Comment by PJEstrada** [comment]
Thanks Anthony! Yes I adjusted the github actions to perform like this, it was a cost savings decision more than anything. But we discuss further what would the ideal flow will look like specially now that we have the autoscaling cluster for the actions

**Comment by anthony-sarkis** [comment]
From Pablo's guidance:
We can manually run the e2e tests on demand too 
https://github.com/diffgram/diffgram/actions/workflows/e2e_tests.yaml

We can review in future as team grows
