### ISSUE TITLE
Secure URL generation improvements

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#923]
We are moving to a pattern of less to no caching of signed URLs to access blobs.

Some of this has already been implemented , such as the addition of `Data_tools.determine_if_should_regenerate_url()` and env var `SIGNED_URL_CACHE_MINIMUM_DAYS_VALID`.

There may be larger refactors but some current ones not covered by this

- Anywhere we update `url_signed_expiry`... basically ensuring that's removed if not actually generating URL
- Anywhere we call `build_secure_url()`. 
Examples, ensuring the concrete storage methods respect env vars, not using fixed values when calling it etc etc 
- Deleting cases in process media. This is done for images but not for the rest of the media types. 95% can just delete it since we already switched to that regen(), but would need to double check serialize methods etc

![image](https://user-images.githubusercontent.com/18080164/173910770-73c7339b-6242-463c-a756-9534b88dfe78.png)

**Comment by anthony-sarkis** [comment]
@PJEstrada Argument: We can close this ticket as it's out of date / already handled. Right or wrong?

**Comment by PJEstrada** [comment]
Yes I think we can close it now
