### ISSUE TITLE
Error creating new connection from Diffgram to local Minio

### ISSUE THREAD

**Issue by Tachimura** [diffgram/diffgram#951]
# Context
I've tried to use Minio (as a local storage provider) with Diffgram but i've encurred in an issue when trying to create a new connection from Diffgram to Minio.

## Setup:

1- Install Minio (I've also tried with the docker version, but got the same error)
wget https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x minio
MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password ./minio server /home/ubuntu/minio_test_data --console-address ":9001"

I have then created a bucket called 'images' and uploaded some data in it.

2- Install Diffgram 1.1.11
git clone https://github.com/diffgram/diffgram.git
cd diffgram
pip install -r requirements.txt
python3 install.py

Selected Minio Web Server Services Storage (which is running in the same machine), inserted the required parameters and the tests: Connection, Write permission and Read permission are OK.

## Error
I logged into Diffgram (from the webpage), tried to create a new connection to Minio, so:
project -> connections -> new connection
I used the same parameters as i've inserted in the install.py but i got this error:

![error](https://user-images.githubusercontent.com/62809228/176541026-3eaed0db-595f-49cc-ba01-443490c4a7aa.jpg)

**Comment by vitalii-bulyzhyn** [comment]
@Tachimura I've just tested it out and everything works for me. The important thing is that you use **http://192.168.20.54:9000** instead of **http://127.0.0.1:9000**

With **http://127.0.0.1:9000** install test will pass, however connection and import won't work

Let me know if that helps

**Comment by Tachimura** [comment]
@vitalii-bulyzhyn I'm pretty sure the env variables are correctly set (here's a snippet of it)
I've added a comment in the image below saying that we tried using both the public ip of our machine and the private one.
Unluckly, the end result is always the same error.
![immagine](https://user-images.githubusercontent.com/62809228/176631514-60080337-81e7-4f29-bd77-4a94999b3dcd.png)

**Comment by PJEstrada** [comment]
Also make sure that the folder you want to write into has write permissions for MinIO.

**Comment by vitalii-bulyzhyn** [comment]
@Tachimura to scope the problem, is the problem only with connection, or file import also doesn't work?

**Comment by Tachimura** [comment]
@PJEstrada Yes, the data directory we are using has write permissions for all users.

@vitalii-bulyzhyn Exactly, we only have problems with the connection to minio. We could import some data into the bucket via the webpage and the python sdk.

**Comment by vitalii-bulyzhyn** [comment]
Okay, in this case the problem may be SSL certificate, can you try to add one as [minio docs](https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html#generate-use-self-signed-keys-certificates) suggest?

**Comment by Tachimura** [comment]
@vitalii-bulyzhyn my team had the machine recreated by zero and after performing all the previous steps it is now working. 
We can now connect to minio, download the bucket and work on it. Probably the problem was caused by some variables not correctly set.

**Comment by vitalii-bulyzhyn** [comment]
Happy everything works now 👍
