### ISSUE TITLE
Saving text global attributes

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#955]
Multi-select type fails
![value error when trying to save globals on text](https://user-images.githubusercontent.com/18080164/176961992-4eb506a3-d22f-497f-82dd-758d1d17f2e9.png)

**Comment by PJEstrada** [comment]
@vitalii-bulyzhyn

**Comment by vitalii-bulyzhyn** [comment]
@PJEstrada just checked, it was fixed before. Closing the issue
