### ISSUE TITLE
Error accessing BLOB

### ISSUE THREAD

**Issue by r19865** [diffgram/diffgram#968]
Hi, I get the following error when I try to access images I've imported into Diffgram. "error: Storage error. Error accessing BLOB". 
I re-imported files from a different Diffgram export. I've tried accessing the URL, but they are not expired. I've also confirmed that I have permission to access and write in the AWS bucket as well. I'm also sharing what I see from my console as well as the network tab. 
![Screen Shot 2022-07-08 at 09 10 41](https://user-images.githubusercontent.com/38407651/178106362-f1b9b834-e43a-48f4-9fcb-d5e2bafc0dc2.png)
![Screen Shot 2022-07-08 at 09 11 09](https://user-images.githubusercontent.com/38407651/178106368-87871b5d-378b-4024-a75d-0afb8f8172de.png)
<img width="1277" alt="Screen Shot 2022-07-07 at 22 09 33" src="https://user-images.githubusercontent.com/38407651/178106378-8549568b-677b-4dc6-b4ad-f636fcaaaa32.png">
![Screen Shot 2022-07-07 at 22 07 41](https://user-images.githubusercontent.com/38407651/178106388-3ae7bb85-a9d6-4f59-abc2-bb6ad5ca4715.png)

**Comment by anthony-sarkis** [comment]
@r19865  What is the output from console when you open that URL by itself in a new window? There should be some kind of error from AWS

**Comment by r19865** [comment]
![Screen Shot 2022-07-12 at 07 47 15](https://user-images.githubusercontent.com/38407651/178372169-a9ac1ad4-30dc-4d0f-9c5e-56cd02fae525.png)
These are the two errors I see when I open the link on a new window and look at the chrome console.

**Comment by PJEstrada** [comment]
It seems that the URL settings is exceeding the offest time.

Try setting:

`SIGNED_URL_CACHE_MINIMUM_DAYS_VALID`

and

`SIGNED_URL_CACHE_NEW_OFFSET_DAYS_VALID`

To something lower that 7 days (in seconds)

You can see the defaults of those values here: 

https://github.com/diffgram/diffgram/blob/9cb78ed66298bf1b309aff09d3c74d9d16785ac6/shared/settings/settings.py#L182-L183

**Comment by anthony-sarkis** [comment]
Cross linked here for future https://diffgram.readme.io/docs/diffgram-aws-installation-problems#blob-access-x-amz-expires-must-be-less-then-a-week

**Comment by r19865** [comment]
Hi Pablo,

Thank you for your advice. Since 7 days = 604800 seconds, I set
SIGNED_URL_CACHE_MINIMUM_DAYS_VALID = 400000 and
SIGNED_URL_CACHE_NEW_OFFSET_DAYS_VALID = 600000 (I've attached a screenshot
of this below).

I exported and reimported a new Diffgram file, just in case the other one
had expired, but I'm still getting the same error. I also notice, in my
terminal that I am getting the following (attached screenshot) "closed TCP
connection" warning, which I'm not sure is related to the issue...

Reina

2022年7月12日(火) 8:05 PJEstrada ***@***.***>:

**Comment by PJEstrada** [comment]
> Thank you for your advice. Since 7 days = 604800 seconds, I set SIGNED_URL_CACHE_MINIMUM_DAYS_VALID = 400000 and SIGNED_URL_CACHE_NEW_OFFSET_DAYS_VALID = 600000 (I've attached a screenshot of this below). I exported and reimported a new Diffgram file, just in case the other one had expired, but I'm still getting the same error. I also notice, in my terminal that I am getting the following (attached screenshot) "closed TCP connection" warning, which I'm not sure is related to the issue... <img width="641" alt="Screen Shot 2022-07-12 at 20 25 27" src="https://user-images.githubusercontent.com/38407651/178480673-aac6e683-09c7-45ad-aef1-b65122daa5d7.png"> <img width="1074" alt="Screen Shot 2022-07-12 at 20 26 03" src="https://user-images.githubusercontent.com/38407651/178480686-4d8cbcdd-73e4-4cec-b94a-69d70c5d049f.png">

* The first error is because your rabbit MQ service might be down. Please check that the container is healthy or try restarting.
* The second screenshot I think that's not quite the correct place to put it if you are running the diffgram service on docker since the files are inside the container and not on the repo folder. You need to set the env variable on the docker container itself by changing the `.env` file on the same folder where the `docker-compose.yaml` is

**Comment by anthony-sarkis** [comment]
@r19865 please re-open with fresh information if issue is not solved
